/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module csac_digital_top(clk_vco, photo_adc, temp_adc, dac_vco_tune, dac_heater_power, spi_clk, spi_mosi, spi_miso, spi_cs, count_1hz, valid_lock, status_byte, reset_n, clk_slow);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire [32:0] _0475_;
  wire [32:0] _0476_;
  input clk_slow;
  wire clk_slow;
  input clk_vco;
  wire clk_vco;
  output [31:0] count_1hz;
  wire [31:0] count_1hz;
  output [7:0] dac_heater_power;
  wire [7:0] dac_heater_power;
  output [9:0] dac_vco_tune;
  wire [9:0] dac_vco_tune;
  wire [3:0] lock_counter;
  input [7:0] photo_adc;
  wire [7:0] photo_adc;
  wire [9:0] pid_integral;
  wire [7:0] pid_last_error;
  input reset_n;
  wire reset_n;
  wire [7:0] spi_addr_latch;
  input spi_clk;
  wire spi_clk;
  input spi_cs;
  wire spi_cs;
  wire [7:0] spi_data_in;
  wire [7:0] spi_data_out;
  output spi_miso;
  wire spi_miso;
  input spi_mosi;
  wire spi_mosi;
  wire spi_rx_valid;
  output [7:0] status_byte;
  wire [7:0] status_byte;
  input [9:0] temp_adc;
  wire [9:0] temp_adc;
  output valid_lock;
  wire valid_lock;
  wire vco_bit26_d;
  wire vco_bit32_d;
  wire [32:0] vco_counter;
  sky130_fd_sc_hd__clkinv_1 _0477_ (
    .A(pid_integral[1]),
    .Y(_0081_)
  );
  sky130_fd_sc_hd__clkinv_1 _0478_ (
    .A(pid_integral[2]),
    .Y(_0082_)
  );
  sky130_fd_sc_hd__clkinv_1 _0479_ (
    .A(pid_integral[4]),
    .Y(_0083_)
  );
  sky130_fd_sc_hd__clkinv_1 _0480_ (
    .A(vco_counter[0]),
    .Y(_0475_[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0481_ (
    .A(status_byte[4]),
    .SLEEP(vco_bit26_d),
    .X(_0084_)
  );
  sky130_fd_sc_hd__nand2b_1 _0482_ (
    .A_N(vco_bit26_d),
    .B(status_byte[4]),
    .Y(_0085_)
  );
  sky130_fd_sc_hd__or3_1 _0483_ (
    .A(photo_adc[2]),
    .B(photo_adc[3]),
    .C(photo_adc[1]),
    .X(_0086_)
  );
  sky130_fd_sc_hd__nand2_1 _0484_ (
    .A(photo_adc[4]),
    .B(_0086_),
    .Y(_0087_)
  );
  sky130_fd_sc_hd__nand3_1 _0485_ (
    .A(photo_adc[4]),
    .B(photo_adc[5]),
    .C(_0086_),
    .Y(_0088_)
  );
  sky130_fd_sc_hd__a31oi_1 _0486_ (
    .A1(photo_adc[4]),
    .A2(photo_adc[5]),
    .A3(_0086_),
    .B1(photo_adc[6]),
    .Y(_0089_)
  );
  sky130_fd_sc_hd__xnor2_1 _0487_ (
    .A(photo_adc[7]),
    .B(_0089_),
    .Y(_0090_)
  );
  sky130_fd_sc_hd__xor2_1 _0488_ (
    .A(photo_adc[7]),
    .B(_0089_),
    .X(_0091_)
  );
  sky130_fd_sc_hd__xnor2_1 _0489_ (
    .A(photo_adc[6]),
    .B(_0088_),
    .Y(_0092_)
  );
  sky130_fd_sc_hd__xor2_1 _0490_ (
    .A(photo_adc[6]),
    .B(_0088_),
    .X(_0093_)
  );
  sky130_fd_sc_hd__xnor2_1 _0491_ (
    .A(photo_adc[5]),
    .B(_0087_),
    .Y(_0094_)
  );
  sky130_fd_sc_hd__xor2_1 _0492_ (
    .A(photo_adc[5]),
    .B(_0087_),
    .X(_0095_)
  );
  sky130_fd_sc_hd__o21ai_0 _0493_ (
    .A1(photo_adc[2]),
    .A2(photo_adc[1]),
    .B1(photo_adc[3]),
    .Y(_0096_)
  );
  sky130_fd_sc_hd__and2_0 _0494_ (
    .A(_0086_),
    .B(_0096_),
    .X(_0097_)
  );
  sky130_fd_sc_hd__xor2_1 _0495_ (
    .A(photo_adc[2]),
    .B(photo_adc[1]),
    .X(_0098_)
  );
  sky130_fd_sc_hd__xnor2_1 _0496_ (
    .A(photo_adc[2]),
    .B(photo_adc[1]),
    .Y(_0099_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0497_ (
    .A(photo_adc[1]),
    .SLEEP(photo_adc[2]),
    .X(_0100_)
  );
  sky130_fd_sc_hd__xor2_1 _0498_ (
    .A(photo_adc[4]),
    .B(_0086_),
    .X(_0101_)
  );
  sky130_fd_sc_hd__clkinv_1 _0499_ (
    .A(_0101_),
    .Y(_0102_)
  );
  sky130_fd_sc_hd__nor4_1 _0500_ (
    .A(_0091_),
    .B(_0093_),
    .C(_0094_),
    .D(_0101_),
    .Y(_0103_)
  );
  sky130_fd_sc_hd__o21ai_0 _0501_ (
    .A1(_0097_),
    .A2(_0100_),
    .B1(_0103_),
    .Y(_0104_)
  );
  sky130_fd_sc_hd__nor4b_1 _0502_ (
    .A(lock_counter[0]),
    .B(lock_counter[1]),
    .C(lock_counter[2]),
    .D_N(lock_counter[3]),
    .Y(_0105_)
  );
  sky130_fd_sc_hd__nand2b_1 _0503_ (
    .A_N(_0104_),
    .B(_0105_),
    .Y(_0106_)
  );
  sky130_fd_sc_hd__and2_0 _0504_ (
    .A(_0084_),
    .B(_0106_),
    .X(_0107_)
  );
  sky130_fd_sc_hd__nand2_1 _0505_ (
    .A(_0084_),
    .B(_0104_),
    .Y(_0108_)
  );
  sky130_fd_sc_hd__nand2_1 _0506_ (
    .A(status_byte[7]),
    .B(_0108_),
    .Y(_0109_)
  );
  sky130_fd_sc_hd__o21ai_0 _0507_ (
    .A1(_0085_),
    .A2(_0106_),
    .B1(_0109_),
    .Y(_0000_)
  );
  sky130_fd_sc_hd__nand2_1 _0508_ (
    .A(dac_heater_power[0]),
    .B(_0085_),
    .Y(_0110_)
  );
  sky130_fd_sc_hd__nand2_1 _0509_ (
    .A(temp_adc[0]),
    .B(temp_adc[1]),
    .Y(_0111_)
  );
  sky130_fd_sc_hd__nand4_1 _0510_ (
    .A(temp_adc[0]),
    .B(temp_adc[1]),
    .C(temp_adc[2]),
    .D(temp_adc[3]),
    .Y(_0112_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0511_ (
    .A(temp_adc[4]),
    .SLEEP(_0112_),
    .X(_0113_)
  );
  sky130_fd_sc_hd__nor2_1 _0512_ (
    .A(temp_adc[5]),
    .B(_0113_),
    .Y(_0114_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0513_ (
    .A(temp_adc[6]),
    .SLEEP(_0114_),
    .X(_0115_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0514_ (
    .A(temp_adc[7]),
    .SLEEP(_0115_),
    .X(_0116_)
  );
  sky130_fd_sc_hd__a21o_1 _0515_ (
    .A1(temp_adc[8]),
    .A2(_0116_),
    .B1(temp_adc[9]),
    .X(_0117_)
  );
  sky130_fd_sc_hd__xnor2_1 _0516_ (
    .A(temp_adc[2]),
    .B(_0111_),
    .Y(_0118_)
  );
  sky130_fd_sc_hd__o31ai_1 _0517_ (
    .A1(_0085_),
    .A2(_0117_),
    .A3(_0118_),
    .B1(_0110_),
    .Y(_0001_)
  );
  sky130_fd_sc_hd__nand2_1 _0518_ (
    .A(dac_heater_power[1]),
    .B(_0085_),
    .Y(_0119_)
  );
  sky130_fd_sc_hd__a31o_1 _0519_ (
    .A1(temp_adc[0]),
    .A2(temp_adc[1]),
    .A3(temp_adc[2]),
    .B1(temp_adc[3]),
    .X(_0120_)
  );
  sky130_fd_sc_hd__a21o_1 _0520_ (
    .A1(_0112_),
    .A2(_0120_),
    .B1(_0085_),
    .X(_0121_)
  );
  sky130_fd_sc_hd__o21ai_0 _0521_ (
    .A1(_0117_),
    .A2(_0121_),
    .B1(_0119_),
    .Y(_0002_)
  );
  sky130_fd_sc_hd__nand2_1 _0522_ (
    .A(dac_heater_power[2]),
    .B(_0085_),
    .Y(_0122_)
  );
  sky130_fd_sc_hd__xnor2_1 _0523_ (
    .A(temp_adc[4]),
    .B(_0112_),
    .Y(_0123_)
  );
  sky130_fd_sc_hd__o31ai_1 _0524_ (
    .A1(_0085_),
    .A2(_0117_),
    .A3(_0123_),
    .B1(_0122_),
    .Y(_0003_)
  );
  sky130_fd_sc_hd__nand2_1 _0525_ (
    .A(dac_heater_power[3]),
    .B(_0085_),
    .Y(_0124_)
  );
  sky130_fd_sc_hd__a21oi_1 _0526_ (
    .A1(temp_adc[5]),
    .A2(_0113_),
    .B1(_0117_),
    .Y(_0125_)
  );
  sky130_fd_sc_hd__nand2_1 _0527_ (
    .A(_0084_),
    .B(_0125_),
    .Y(_0126_)
  );
  sky130_fd_sc_hd__o21ai_0 _0528_ (
    .A1(_0114_),
    .A2(_0126_),
    .B1(_0124_),
    .Y(_0004_)
  );
  sky130_fd_sc_hd__nand2_1 _0529_ (
    .A(dac_heater_power[4]),
    .B(_0085_),
    .Y(_0127_)
  );
  sky130_fd_sc_hd__xnor2_1 _0530_ (
    .A(temp_adc[6]),
    .B(_0114_),
    .Y(_0128_)
  );
  sky130_fd_sc_hd__o31ai_1 _0531_ (
    .A1(_0085_),
    .A2(_0117_),
    .A3(_0128_),
    .B1(_0127_),
    .Y(_0005_)
  );
  sky130_fd_sc_hd__a211oi_1 _0532_ (
    .A1(temp_adc[7]),
    .A2(_0115_),
    .B1(_0117_),
    .C1(_0085_),
    .Y(_0129_)
  );
  sky130_fd_sc_hd__a22o_1 _0533_ (
    .A1(dac_heater_power[5]),
    .A2(_0085_),
    .B1(_0116_),
    .B2(_0129_),
    .X(_0006_)
  );
  sky130_fd_sc_hd__nand2_1 _0534_ (
    .A(dac_heater_power[6]),
    .B(_0085_),
    .Y(_0130_)
  );
  sky130_fd_sc_hd__o41ai_1 _0535_ (
    .A1(temp_adc[8]),
    .A2(temp_adc[9]),
    .A3(_0085_),
    .A4(_0116_),
    .B1(_0130_),
    .Y(_0007_)
  );
  sky130_fd_sc_hd__and2_0 _0536_ (
    .A(dac_heater_power[7]),
    .B(_0085_),
    .X(_0008_)
  );
  sky130_fd_sc_hd__nor4_1 _0537_ (
    .A(lock_counter[0]),
    .B(_0085_),
    .C(_0104_),
    .D(_0105_),
    .Y(_0131_)
  );
  sky130_fd_sc_hd__a21o_1 _0538_ (
    .A1(lock_counter[0]),
    .A2(_0085_),
    .B1(_0131_),
    .X(_0009_)
  );
  sky130_fd_sc_hd__xnor2_1 _0539_ (
    .A(lock_counter[0]),
    .B(lock_counter[1]),
    .Y(_0132_)
  );
  sky130_fd_sc_hd__o21ai_0 _0540_ (
    .A1(_0104_),
    .A2(_0132_),
    .B1(_0107_),
    .Y(_0133_)
  );
  sky130_fd_sc_hd__o21a_1 _0541_ (
    .A1(lock_counter[1]),
    .A2(_0107_),
    .B1(_0133_),
    .X(_0010_)
  );
  sky130_fd_sc_hd__nor2_1 _0542_ (
    .A(lock_counter[2]),
    .B(_0107_),
    .Y(_0134_)
  );
  sky130_fd_sc_hd__a21oi_1 _0543_ (
    .A1(lock_counter[0]),
    .A2(lock_counter[1]),
    .B1(lock_counter[2]),
    .Y(_0135_)
  );
  sky130_fd_sc_hd__and3_1 _0544_ (
    .A(lock_counter[0]),
    .B(lock_counter[1]),
    .C(lock_counter[2]),
    .X(_0136_)
  );
  sky130_fd_sc_hd__or3_1 _0545_ (
    .A(_0104_),
    .B(_0135_),
    .C(_0136_),
    .X(_0137_)
  );
  sky130_fd_sc_hd__a21oi_1 _0546_ (
    .A1(_0107_),
    .A2(_0137_),
    .B1(_0134_),
    .Y(_0011_)
  );
  sky130_fd_sc_hd__a21oi_1 _0547_ (
    .A1(_0084_),
    .A2(_0136_),
    .B1(lock_counter[3]),
    .Y(_0138_)
  );
  sky130_fd_sc_hd__a21o_1 _0548_ (
    .A1(_0084_),
    .A2(_0104_),
    .B1(_0138_),
    .X(_0139_)
  );
  sky130_fd_sc_hd__a31oi_1 _0549_ (
    .A1(lock_counter[3]),
    .A2(_0107_),
    .A3(_0136_),
    .B1(_0139_),
    .Y(_0012_)
  );
  sky130_fd_sc_hd__nand2_1 _0550_ (
    .A(pid_integral[3]),
    .B(_0094_),
    .Y(_0140_)
  );
  sky130_fd_sc_hd__nand2_1 _0551_ (
    .A(pid_integral[0]),
    .B(_0099_),
    .Y(_0141_)
  );
  sky130_fd_sc_hd__xnor2_1 _0552_ (
    .A(pid_integral[1]),
    .B(_0097_),
    .Y(_0142_)
  );
  sky130_fd_sc_hd__maj3_1 _0553_ (
    .A(_0081_),
    .B(_0097_),
    .C(_0141_),
    .X(_0143_)
  );
  sky130_fd_sc_hd__xnor2_1 _0554_ (
    .A(_0082_),
    .B(_0101_),
    .Y(_0144_)
  );
  sky130_fd_sc_hd__maj3_1 _0555_ (
    .A(_0082_),
    .B(_0102_),
    .C(_0143_),
    .X(_0145_)
  );
  sky130_fd_sc_hd__nor2_1 _0556_ (
    .A(pid_integral[3]),
    .B(_0094_),
    .Y(_0146_)
  );
  sky130_fd_sc_hd__o21ai_0 _0557_ (
    .A1(_0145_),
    .A2(_0146_),
    .B1(_0140_),
    .Y(_0147_)
  );
  sky130_fd_sc_hd__xnor2_1 _0558_ (
    .A(_0083_),
    .B(_0092_),
    .Y(_0148_)
  );
  sky130_fd_sc_hd__maj3_1 _0559_ (
    .A(pid_integral[4]),
    .B(_0093_),
    .C(_0147_),
    .X(_0149_)
  );
  sky130_fd_sc_hd__maj3_1 _0560_ (
    .A(pid_integral[5]),
    .B(_0091_),
    .C(_0149_),
    .X(_0150_)
  );
  sky130_fd_sc_hd__nand3_1 _0561_ (
    .A(status_byte[0]),
    .B(status_byte[1]),
    .C(_0150_),
    .Y(_0151_)
  );
  sky130_fd_sc_hd__nand2_1 _0562_ (
    .A(status_byte[2]),
    .B(status_byte[3]),
    .Y(_0152_)
  );
  sky130_fd_sc_hd__nor2_1 _0563_ (
    .A(_0151_),
    .B(_0152_),
    .Y(_0153_)
  );
  sky130_fd_sc_hd__nand2_1 _0564_ (
    .A(_0084_),
    .B(_0153_),
    .Y(_0154_)
  );
  sky130_fd_sc_hd__nand2_1 _0565_ (
    .A(_0084_),
    .B(_0099_),
    .Y(_0155_)
  );
  sky130_fd_sc_hd__xor2_1 _0566_ (
    .A(pid_integral[0]),
    .B(_0155_),
    .X(_0156_)
  );
  sky130_fd_sc_hd__nand2_1 _0567_ (
    .A(_0154_),
    .B(_0156_),
    .Y(_0013_)
  );
  sky130_fd_sc_hd__xnor2_1 _0568_ (
    .A(_0141_),
    .B(_0142_),
    .Y(_0157_)
  );
  sky130_fd_sc_hd__o21ai_0 _0569_ (
    .A1(_0153_),
    .A2(_0157_),
    .B1(_0084_),
    .Y(_0158_)
  );
  sky130_fd_sc_hd__o21ai_0 _0570_ (
    .A1(_0081_),
    .A2(_0084_),
    .B1(_0158_),
    .Y(_0014_)
  );
  sky130_fd_sc_hd__xnor2_1 _0571_ (
    .A(_0143_),
    .B(_0144_),
    .Y(_0159_)
  );
  sky130_fd_sc_hd__o21ai_0 _0572_ (
    .A1(_0153_),
    .A2(_0159_),
    .B1(_0084_),
    .Y(_0160_)
  );
  sky130_fd_sc_hd__o21ai_0 _0573_ (
    .A1(_0082_),
    .A2(_0084_),
    .B1(_0160_),
    .Y(_0015_)
  );
  sky130_fd_sc_hd__nand2_1 _0574_ (
    .A(pid_integral[3]),
    .B(_0085_),
    .Y(_0161_)
  );
  sky130_fd_sc_hd__xnor2_1 _0575_ (
    .A(pid_integral[3]),
    .B(_0095_),
    .Y(_0162_)
  );
  sky130_fd_sc_hd__xnor2_1 _0576_ (
    .A(_0145_),
    .B(_0162_),
    .Y(_0163_)
  );
  sky130_fd_sc_hd__o21ai_0 _0577_ (
    .A1(_0153_),
    .A2(_0163_),
    .B1(_0084_),
    .Y(_0164_)
  );
  sky130_fd_sc_hd__nand2_1 _0578_ (
    .A(_0161_),
    .B(_0164_),
    .Y(_0016_)
  );
  sky130_fd_sc_hd__xnor2_1 _0579_ (
    .A(_0147_),
    .B(_0148_),
    .Y(_0165_)
  );
  sky130_fd_sc_hd__o21ai_0 _0580_ (
    .A1(_0153_),
    .A2(_0165_),
    .B1(_0084_),
    .Y(_0166_)
  );
  sky130_fd_sc_hd__o21ai_0 _0581_ (
    .A1(_0083_),
    .A2(_0084_),
    .B1(_0166_),
    .Y(_0017_)
  );
  sky130_fd_sc_hd__nand2_1 _0582_ (
    .A(pid_integral[5]),
    .B(_0085_),
    .Y(_0167_)
  );
  sky130_fd_sc_hd__xnor2_1 _0583_ (
    .A(pid_integral[5]),
    .B(_0091_),
    .Y(_0168_)
  );
  sky130_fd_sc_hd__xnor2_1 _0584_ (
    .A(_0149_),
    .B(_0168_),
    .Y(_0169_)
  );
  sky130_fd_sc_hd__o21ai_0 _0585_ (
    .A1(_0153_),
    .A2(_0169_),
    .B1(_0084_),
    .Y(_0170_)
  );
  sky130_fd_sc_hd__nand2_1 _0586_ (
    .A(_0167_),
    .B(_0170_),
    .Y(_0018_)
  );
  sky130_fd_sc_hd__and3_1 _0587_ (
    .A(status_byte[0]),
    .B(_0084_),
    .C(_0150_),
    .X(_0171_)
  );
  sky130_fd_sc_hd__a21oi_1 _0588_ (
    .A1(_0084_),
    .A2(_0150_),
    .B1(status_byte[0]),
    .Y(_0172_)
  );
  sky130_fd_sc_hd__o21ai_0 _0589_ (
    .A1(_0171_),
    .A2(_0172_),
    .B1(_0154_),
    .Y(_0019_)
  );
  sky130_fd_sc_hd__nor2_1 _0590_ (
    .A(_0085_),
    .B(_0151_),
    .Y(_0173_)
  );
  sky130_fd_sc_hd__nor2_1 _0591_ (
    .A(status_byte[1]),
    .B(_0171_),
    .Y(_0174_)
  );
  sky130_fd_sc_hd__o21ai_0 _0592_ (
    .A1(_0173_),
    .A2(_0174_),
    .B1(_0154_),
    .Y(_0020_)
  );
  sky130_fd_sc_hd__nor2_1 _0593_ (
    .A(status_byte[2]),
    .B(_0173_),
    .Y(_0175_)
  );
  sky130_fd_sc_hd__nand2_1 _0594_ (
    .A(status_byte[2]),
    .B(_0173_),
    .Y(_0176_)
  );
  sky130_fd_sc_hd__nor2_1 _0595_ (
    .A(status_byte[3]),
    .B(_0176_),
    .Y(_0177_)
  );
  sky130_fd_sc_hd__nor2_1 _0596_ (
    .A(_0175_),
    .B(_0177_),
    .Y(_0021_)
  );
  sky130_fd_sc_hd__nand2b_1 _0597_ (
    .A_N(status_byte[3]),
    .B(_0176_),
    .Y(_0022_)
  );
  sky130_fd_sc_hd__nand2_1 _0598_ (
    .A(pid_last_error[0]),
    .B(_0085_),
    .Y(_0178_)
  );
  sky130_fd_sc_hd__nand2_1 _0599_ (
    .A(photo_adc[0]),
    .B(_0084_),
    .Y(_0179_)
  );
  sky130_fd_sc_hd__nand2_1 _0600_ (
    .A(_0178_),
    .B(_0179_),
    .Y(_0023_)
  );
  sky130_fd_sc_hd__nand2_1 _0601_ (
    .A(pid_last_error[1]),
    .B(_0085_),
    .Y(_0180_)
  );
  sky130_fd_sc_hd__o21ai_0 _0602_ (
    .A1(photo_adc[1]),
    .A2(_0085_),
    .B1(_0180_),
    .Y(_0024_)
  );
  sky130_fd_sc_hd__nand2_1 _0603_ (
    .A(pid_last_error[2]),
    .B(_0085_),
    .Y(_0181_)
  );
  sky130_fd_sc_hd__nand2_1 _0604_ (
    .A(_0155_),
    .B(_0181_),
    .Y(_0025_)
  );
  sky130_fd_sc_hd__nand2_1 _0605_ (
    .A(pid_last_error[3]),
    .B(_0085_),
    .Y(_0182_)
  );
  sky130_fd_sc_hd__o21ai_0 _0606_ (
    .A1(_0085_),
    .A2(_0097_),
    .B1(_0182_),
    .Y(_0026_)
  );
  sky130_fd_sc_hd__nand2_1 _0607_ (
    .A(pid_last_error[4]),
    .B(_0085_),
    .Y(_0183_)
  );
  sky130_fd_sc_hd__o21ai_0 _0608_ (
    .A1(_0085_),
    .A2(_0102_),
    .B1(_0183_),
    .Y(_0027_)
  );
  sky130_fd_sc_hd__nand2_1 _0609_ (
    .A(pid_last_error[5]),
    .B(_0085_),
    .Y(_0184_)
  );
  sky130_fd_sc_hd__o21ai_0 _0610_ (
    .A1(_0085_),
    .A2(_0095_),
    .B1(_0184_),
    .Y(_0028_)
  );
  sky130_fd_sc_hd__nand2_1 _0611_ (
    .A(pid_last_error[6]),
    .B(_0085_),
    .Y(_0185_)
  );
  sky130_fd_sc_hd__o21ai_0 _0612_ (
    .A1(_0085_),
    .A2(_0092_),
    .B1(_0185_),
    .Y(_0029_)
  );
  sky130_fd_sc_hd__nand2_1 _0613_ (
    .A(pid_last_error[7]),
    .B(_0085_),
    .Y(_0186_)
  );
  sky130_fd_sc_hd__o21ai_0 _0614_ (
    .A1(_0085_),
    .A2(_0090_),
    .B1(_0186_),
    .Y(_0030_)
  );
  sky130_fd_sc_hd__xnor2_1 _0615_ (
    .A(pid_last_error[7]),
    .B(_0091_),
    .Y(_0187_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0616_ (
    .A(pid_last_error[0]),
    .SLEEP(photo_adc[0]),
    .X(_0188_)
  );
  sky130_fd_sc_hd__xor2_1 _0617_ (
    .A(pid_last_error[1]),
    .B(photo_adc[1]),
    .X(_0189_)
  );
  sky130_fd_sc_hd__maj3_1 _0618_ (
    .A(pid_last_error[1]),
    .B(photo_adc[1]),
    .C(_0188_),
    .X(_0190_)
  );
  sky130_fd_sc_hd__xnor2_1 _0619_ (
    .A(pid_last_error[2]),
    .B(_0099_),
    .Y(_0191_)
  );
  sky130_fd_sc_hd__maj3_1 _0620_ (
    .A(pid_last_error[2]),
    .B(_0098_),
    .C(_0190_),
    .X(_0192_)
  );
  sky130_fd_sc_hd__maj3_1 _0621_ (
    .A(pid_last_error[3]),
    .B(_0097_),
    .C(_0192_),
    .X(_0193_)
  );
  sky130_fd_sc_hd__xnor2_1 _0622_ (
    .A(pid_last_error[4]),
    .B(_0101_),
    .Y(_0194_)
  );
  sky130_fd_sc_hd__maj3_1 _0623_ (
    .A(pid_last_error[4]),
    .B(_0102_),
    .C(_0193_),
    .X(_0195_)
  );
  sky130_fd_sc_hd__maj3_1 _0624_ (
    .A(pid_last_error[5]),
    .B(_0095_),
    .C(_0195_),
    .X(_0196_)
  );
  sky130_fd_sc_hd__xnor2_1 _0625_ (
    .A(pid_last_error[6]),
    .B(_0093_),
    .Y(_0197_)
  );
  sky130_fd_sc_hd__maj3_1 _0626_ (
    .A(pid_last_error[6]),
    .B(_0092_),
    .C(_0196_),
    .X(_0198_)
  );
  sky130_fd_sc_hd__maj3_1 _0627_ (
    .A(pid_last_error[7]),
    .B(_0090_),
    .C(_0198_),
    .X(_0199_)
  );
  sky130_fd_sc_hd__xnor2_1 _0628_ (
    .A(pid_integral[3]),
    .B(_0098_),
    .Y(_0200_)
  );
  sky130_fd_sc_hd__nand2b_1 _0629_ (
    .A_N(photo_adc[1]),
    .B(pid_integral[2]),
    .Y(_0201_)
  );
  sky130_fd_sc_hd__nand2_1 _0630_ (
    .A(pid_integral[1]),
    .B(photo_adc[0]),
    .Y(_0202_)
  );
  sky130_fd_sc_hd__xor2_1 _0631_ (
    .A(pid_integral[2]),
    .B(photo_adc[1]),
    .X(_0203_)
  );
  sky130_fd_sc_hd__o21ai_0 _0632_ (
    .A1(_0202_),
    .A2(_0203_),
    .B1(_0201_),
    .Y(_0204_)
  );
  sky130_fd_sc_hd__maj3_1 _0633_ (
    .A(pid_integral[3]),
    .B(_0099_),
    .C(_0204_),
    .X(_0205_)
  );
  sky130_fd_sc_hd__xnor2_1 _0634_ (
    .A(pid_integral[4]),
    .B(_0097_),
    .Y(_0206_)
  );
  sky130_fd_sc_hd__nand2_1 _0635_ (
    .A(_0205_),
    .B(_0206_),
    .Y(_0207_)
  );
  sky130_fd_sc_hd__o21ai_0 _0636_ (
    .A1(_0083_),
    .A2(_0097_),
    .B1(_0207_),
    .Y(_0208_)
  );
  sky130_fd_sc_hd__maj3_1 _0637_ (
    .A(pid_integral[5]),
    .B(_0101_),
    .C(_0208_),
    .X(_0209_)
  );
  sky130_fd_sc_hd__xnor2_1 _0638_ (
    .A(status_byte[0]),
    .B(_0095_),
    .Y(_0210_)
  );
  sky130_fd_sc_hd__maj3_1 _0639_ (
    .A(status_byte[0]),
    .B(_0094_),
    .C(_0209_),
    .X(_0211_)
  );
  sky130_fd_sc_hd__xnor2_1 _0640_ (
    .A(status_byte[1]),
    .B(_0092_),
    .Y(_0212_)
  );
  sky130_fd_sc_hd__maj3_1 _0641_ (
    .A(status_byte[1]),
    .B(_0093_),
    .C(_0211_),
    .X(_0213_)
  );
  sky130_fd_sc_hd__xnor2_1 _0642_ (
    .A(status_byte[2]),
    .B(_0090_),
    .Y(_0214_)
  );
  sky130_fd_sc_hd__maj3_1 _0643_ (
    .A(status_byte[2]),
    .B(_0091_),
    .C(_0213_),
    .X(_0215_)
  );
  sky130_fd_sc_hd__nand2_1 _0644_ (
    .A(status_byte[3]),
    .B(_0215_),
    .Y(_0216_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0645_ (
    .A(_0199_),
    .SLEEP(_0216_),
    .X(_0217_)
  );
  sky130_fd_sc_hd__and2_0 _0646_ (
    .A(_0199_),
    .B(_0216_),
    .X(_0218_)
  );
  sky130_fd_sc_hd__xnor2_1 _0647_ (
    .A(_0190_),
    .B(_0191_),
    .Y(_0219_)
  );
  sky130_fd_sc_hd__xnor2_1 _0648_ (
    .A(_0188_),
    .B(_0189_),
    .Y(_0220_)
  );
  sky130_fd_sc_hd__nand2_1 _0649_ (
    .A(_0219_),
    .B(_0220_),
    .Y(_0221_)
  );
  sky130_fd_sc_hd__xor2_1 _0650_ (
    .A(pid_last_error[3]),
    .B(_0097_),
    .X(_0222_)
  );
  sky130_fd_sc_hd__xnor2_1 _0651_ (
    .A(_0192_),
    .B(_0222_),
    .Y(_0223_)
  );
  sky130_fd_sc_hd__nand2_1 _0652_ (
    .A(_0219_),
    .B(_0223_),
    .Y(_0224_)
  );
  sky130_fd_sc_hd__nand3b_1 _0653_ (
    .A_N(_0223_),
    .B(_0220_),
    .C(_0219_),
    .Y(_0225_)
  );
  sky130_fd_sc_hd__xnor2_1 _0654_ (
    .A(_0193_),
    .B(_0194_),
    .Y(_0226_)
  );
  sky130_fd_sc_hd__nand2_1 _0655_ (
    .A(_0223_),
    .B(_0226_),
    .Y(_0227_)
  );
  sky130_fd_sc_hd__nand3b_1 _0656_ (
    .A_N(_0226_),
    .B(_0223_),
    .C(_0219_),
    .Y(_0228_)
  );
  sky130_fd_sc_hd__xnor3_1 _0657_ (
    .A(_0223_),
    .B(_0224_),
    .C(_0226_),
    .X(_0229_)
  );
  sky130_fd_sc_hd__nand2b_1 _0658_ (
    .A_N(_0225_),
    .B(_0229_),
    .Y(_0230_)
  );
  sky130_fd_sc_hd__xnor2_1 _0659_ (
    .A(pid_last_error[5]),
    .B(_0094_),
    .Y(_0231_)
  );
  sky130_fd_sc_hd__xor2_1 _0660_ (
    .A(_0195_),
    .B(_0231_),
    .X(_0232_)
  );
  sky130_fd_sc_hd__xnor2_1 _0661_ (
    .A(_0195_),
    .B(_0231_),
    .Y(_0233_)
  );
  sky130_fd_sc_hd__nand2_1 _0662_ (
    .A(_0226_),
    .B(_0233_),
    .Y(_0234_)
  );
  sky130_fd_sc_hd__nand3_1 _0663_ (
    .A(_0223_),
    .B(_0226_),
    .C(_0232_),
    .Y(_0235_)
  );
  sky130_fd_sc_hd__xnor3_1 _0664_ (
    .A(_0226_),
    .B(_0227_),
    .C(_0233_),
    .X(_0236_)
  );
  sky130_fd_sc_hd__nand2b_1 _0665_ (
    .A_N(_0228_),
    .B(_0236_),
    .Y(_0237_)
  );
  sky130_fd_sc_hd__xnor2_1 _0666_ (
    .A(_0228_),
    .B(_0236_),
    .Y(_0238_)
  );
  sky130_fd_sc_hd__nor2b_1 _0667_ (
    .A(_0230_),
    .B_N(_0238_),
    .Y(_0239_)
  );
  sky130_fd_sc_hd__xnor2_1 _0668_ (
    .A(_0196_),
    .B(_0197_),
    .Y(_0240_)
  );
  sky130_fd_sc_hd__nand2_1 _0669_ (
    .A(_0232_),
    .B(_0240_),
    .Y(_0241_)
  );
  sky130_fd_sc_hd__xnor3_1 _0670_ (
    .A(_0196_),
    .B(_0197_),
    .C(_0232_),
    .X(_0242_)
  );
  sky130_fd_sc_hd__nor2_1 _0671_ (
    .A(_0234_),
    .B(_0242_),
    .Y(_0243_)
  );
  sky130_fd_sc_hd__xnor2_1 _0672_ (
    .A(_0234_),
    .B(_0242_),
    .Y(_0244_)
  );
  sky130_fd_sc_hd__nand4_1 _0673_ (
    .A(_0223_),
    .B(_0226_),
    .C(_0232_),
    .D(_0240_),
    .Y(_0245_)
  );
  sky130_fd_sc_hd__clkinv_1 _0674_ (
    .A(_0245_),
    .Y(_0246_)
  );
  sky130_fd_sc_hd__nand2_1 _0675_ (
    .A(_0235_),
    .B(_0244_),
    .Y(_0247_)
  );
  sky130_fd_sc_hd__xor2_1 _0676_ (
    .A(_0235_),
    .B(_0244_),
    .X(_0248_)
  );
  sky130_fd_sc_hd__nand2b_1 _0677_ (
    .A_N(_0237_),
    .B(_0248_),
    .Y(_0249_)
  );
  sky130_fd_sc_hd__xnor2_1 _0678_ (
    .A(_0237_),
    .B(_0248_),
    .Y(_0250_)
  );
  sky130_fd_sc_hd__and2_0 _0679_ (
    .A(_0239_),
    .B(_0250_),
    .X(_0251_)
  );
  sky130_fd_sc_hd__xnor2_1 _0680_ (
    .A(_0187_),
    .B(_0198_),
    .Y(_0252_)
  );
  sky130_fd_sc_hd__xnor2_1 _0681_ (
    .A(_0241_),
    .B(_0252_),
    .Y(_0253_)
  );
  sky130_fd_sc_hd__nand2_1 _0682_ (
    .A(_0243_),
    .B(_0253_),
    .Y(_0254_)
  );
  sky130_fd_sc_hd__xor2_1 _0683_ (
    .A(_0243_),
    .B(_0253_),
    .X(_0255_)
  );
  sky130_fd_sc_hd__nand2_1 _0684_ (
    .A(_0246_),
    .B(_0255_),
    .Y(_0256_)
  );
  sky130_fd_sc_hd__nor2_1 _0685_ (
    .A(_0246_),
    .B(_0255_),
    .Y(_0257_)
  );
  sky130_fd_sc_hd__nand4b_1 _0686_ (
    .A_N(_0237_),
    .B(_0245_),
    .C(_0247_),
    .D(_0255_),
    .Y(_0258_)
  );
  sky130_fd_sc_hd__xnor3_1 _0687_ (
    .A(_0246_),
    .B(_0249_),
    .C(_0255_),
    .X(_0259_)
  );
  sky130_fd_sc_hd__xor2_1 _0688_ (
    .A(pid_last_error[0]),
    .B(photo_adc[0]),
    .X(_0260_)
  );
  sky130_fd_sc_hd__nand2_1 _0689_ (
    .A(_0220_),
    .B(_0260_),
    .Y(_0261_)
  );
  sky130_fd_sc_hd__xnor2_1 _0690_ (
    .A(_0219_),
    .B(_0220_),
    .Y(_0262_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0691_ (
    .A(_0261_),
    .SLEEP(_0262_),
    .X(_0263_)
  );
  sky130_fd_sc_hd__xnor3_1 _0692_ (
    .A(_0219_),
    .B(_0221_),
    .C(_0223_),
    .X(_0264_)
  );
  sky130_fd_sc_hd__nor2b_1 _0693_ (
    .A(_0263_),
    .B_N(_0264_),
    .Y(_0265_)
  );
  sky130_fd_sc_hd__xnor2_1 _0694_ (
    .A(_0225_),
    .B(_0229_),
    .Y(_0266_)
  );
  sky130_fd_sc_hd__and2_0 _0695_ (
    .A(_0265_),
    .B(_0266_),
    .X(_0267_)
  );
  sky130_fd_sc_hd__xnor2_1 _0696_ (
    .A(_0230_),
    .B(_0238_),
    .Y(_0268_)
  );
  sky130_fd_sc_hd__nand2_1 _0697_ (
    .A(_0267_),
    .B(_0268_),
    .Y(_0269_)
  );
  sky130_fd_sc_hd__xnor3_1 _0698_ (
    .A(_0237_),
    .B(_0239_),
    .C(_0248_),
    .X(_0270_)
  );
  sky130_fd_sc_hd__nor2b_1 _0699_ (
    .A(_0269_),
    .B_N(_0270_),
    .Y(_0271_)
  );
  sky130_fd_sc_hd__maj3_1 _0700_ (
    .A(_0251_),
    .B(_0259_),
    .C(_0271_),
    .X(_0272_)
  );
  sky130_fd_sc_hd__nand2_1 _0701_ (
    .A(_0233_),
    .B(_0240_),
    .Y(_0273_)
  );
  sky130_fd_sc_hd__a21oi_1 _0702_ (
    .A1(_0233_),
    .A2(_0240_),
    .B1(_0252_),
    .Y(_0274_)
  );
  sky130_fd_sc_hd__mux2i_1 _0703_ (
    .A0(_0273_),
    .A1(_0240_),
    .S(_0252_),
    .Y(_0275_)
  );
  sky130_fd_sc_hd__xnor2_1 _0704_ (
    .A(_0199_),
    .B(_0275_),
    .Y(_0276_)
  );
  sky130_fd_sc_hd__xnor2_1 _0705_ (
    .A(_0254_),
    .B(_0276_),
    .Y(_0277_)
  );
  sky130_fd_sc_hd__nor4b_1 _0706_ (
    .A(_0249_),
    .B(_0277_),
    .C(_0257_),
    .D_N(_0256_),
    .Y(_0278_)
  );
  sky130_fd_sc_hd__xnor3_1 _0707_ (
    .A(_0256_),
    .B(_0258_),
    .C(_0277_),
    .X(_0279_)
  );
  sky130_fd_sc_hd__a21oi_1 _0708_ (
    .A1(_0240_),
    .A2(_0252_),
    .B1(_0199_),
    .Y(_0280_)
  );
  sky130_fd_sc_hd__o22a_1 _0709_ (
    .A1(_0254_),
    .A2(_0276_),
    .B1(_0280_),
    .B2(_0274_),
    .X(_0281_)
  );
  sky130_fd_sc_hd__o21ai_0 _0710_ (
    .A1(_0256_),
    .A2(_0277_),
    .B1(_0281_),
    .Y(_0282_)
  );
  sky130_fd_sc_hd__a211oi_1 _0711_ (
    .A1(_0272_),
    .A2(_0279_),
    .B1(_0282_),
    .C1(_0278_),
    .Y(_0283_)
  );
  sky130_fd_sc_hd__xnor2_1 _0712_ (
    .A(status_byte[3]),
    .B(_0215_),
    .Y(_0284_)
  );
  sky130_fd_sc_hd__xnor2_1 _0713_ (
    .A(_0283_),
    .B(_0284_),
    .Y(_0285_)
  );
  sky130_fd_sc_hd__xnor2_1 _0714_ (
    .A(_0272_),
    .B(_0279_),
    .Y(_0286_)
  );
  sky130_fd_sc_hd__xnor2_1 _0715_ (
    .A(_0213_),
    .B(_0214_),
    .Y(_0287_)
  );
  sky130_fd_sc_hd__xnor3_1 _0716_ (
    .A(_0251_),
    .B(_0259_),
    .C(_0271_),
    .X(_0288_)
  );
  sky130_fd_sc_hd__xnor2_1 _0717_ (
    .A(_0211_),
    .B(_0212_),
    .Y(_0289_)
  );
  sky130_fd_sc_hd__xnor2_1 _0718_ (
    .A(_0288_),
    .B(_0289_),
    .Y(_0290_)
  );
  sky130_fd_sc_hd__xor2_1 _0719_ (
    .A(_0269_),
    .B(_0270_),
    .X(_0291_)
  );
  sky130_fd_sc_hd__xnor2_1 _0720_ (
    .A(_0209_),
    .B(_0210_),
    .Y(_0292_)
  );
  sky130_fd_sc_hd__xor2_1 _0721_ (
    .A(pid_integral[5]),
    .B(_0101_),
    .X(_0293_)
  );
  sky130_fd_sc_hd__xnor2_1 _0722_ (
    .A(_0208_),
    .B(_0293_),
    .Y(_0294_)
  );
  sky130_fd_sc_hd__xnor3_1 _0723_ (
    .A(_0230_),
    .B(_0238_),
    .C(_0267_),
    .X(_0295_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0724_ (
    .A(_0295_),
    .SLEEP(_0294_),
    .X(_0296_)
  );
  sky130_fd_sc_hd__nor2_1 _0725_ (
    .A(_0265_),
    .B(_0266_),
    .Y(_0297_)
  );
  sky130_fd_sc_hd__nor2_1 _0726_ (
    .A(_0267_),
    .B(_0297_),
    .Y(_0298_)
  );
  sky130_fd_sc_hd__xnor2_1 _0727_ (
    .A(_0205_),
    .B(_0206_),
    .Y(_0299_)
  );
  sky130_fd_sc_hd__clkinv_1 _0728_ (
    .A(_0299_),
    .Y(_0300_)
  );
  sky130_fd_sc_hd__xnor2_1 _0729_ (
    .A(_0263_),
    .B(_0264_),
    .Y(_0301_)
  );
  sky130_fd_sc_hd__xor2_1 _0730_ (
    .A(_0200_),
    .B(_0204_),
    .X(_0302_)
  );
  sky130_fd_sc_hd__nand2_1 _0731_ (
    .A(_0301_),
    .B(_0302_),
    .Y(_0303_)
  );
  sky130_fd_sc_hd__xnor2_1 _0732_ (
    .A(_0261_),
    .B(_0262_),
    .Y(_0304_)
  );
  sky130_fd_sc_hd__xor2_1 _0733_ (
    .A(_0202_),
    .B(_0203_),
    .X(_0305_)
  );
  sky130_fd_sc_hd__nor2b_1 _0734_ (
    .A(_0304_),
    .B_N(_0305_),
    .Y(_0306_)
  );
  sky130_fd_sc_hd__xnor2_1 _0735_ (
    .A(_0220_),
    .B(_0260_),
    .Y(_0307_)
  );
  sky130_fd_sc_hd__xnor2_1 _0736_ (
    .A(pid_integral[1]),
    .B(photo_adc[0]),
    .Y(_0308_)
  );
  sky130_fd_sc_hd__nand2_1 _0737_ (
    .A(pid_integral[0]),
    .B(_0260_),
    .Y(_0309_)
  );
  sky130_fd_sc_hd__maj3_1 _0738_ (
    .A(_0307_),
    .B(_0308_),
    .C(_0309_),
    .X(_0310_)
  );
  sky130_fd_sc_hd__xor2_1 _0739_ (
    .A(_0304_),
    .B(_0305_),
    .X(_0311_)
  );
  sky130_fd_sc_hd__nor2_1 _0740_ (
    .A(_0310_),
    .B(_0311_),
    .Y(_0312_)
  );
  sky130_fd_sc_hd__xor2_1 _0741_ (
    .A(_0301_),
    .B(_0302_),
    .X(_0313_)
  );
  sky130_fd_sc_hd__o21ai_0 _0742_ (
    .A1(_0306_),
    .A2(_0312_),
    .B1(_0313_),
    .Y(_0314_)
  );
  sky130_fd_sc_hd__nand2_1 _0743_ (
    .A(_0303_),
    .B(_0314_),
    .Y(_0315_)
  );
  sky130_fd_sc_hd__maj3_1 _0744_ (
    .A(_0298_),
    .B(_0300_),
    .C(_0315_),
    .X(_0316_)
  );
  sky130_fd_sc_hd__nand2b_1 _0745_ (
    .A_N(_0295_),
    .B(_0294_),
    .Y(_0317_)
  );
  sky130_fd_sc_hd__a21oi_1 _0746_ (
    .A1(_0316_),
    .A2(_0317_),
    .B1(_0296_),
    .Y(_0318_)
  );
  sky130_fd_sc_hd__xnor2_1 _0747_ (
    .A(_0291_),
    .B(_0292_),
    .Y(_0319_)
  );
  sky130_fd_sc_hd__maj3_1 _0748_ (
    .A(_0291_),
    .B(_0292_),
    .C(_0318_),
    .X(_0320_)
  );
  sky130_fd_sc_hd__maj3_1 _0749_ (
    .A(_0288_),
    .B(_0289_),
    .C(_0320_),
    .X(_0321_)
  );
  sky130_fd_sc_hd__xnor2_1 _0750_ (
    .A(_0286_),
    .B(_0287_),
    .Y(_0322_)
  );
  sky130_fd_sc_hd__maj3_1 _0751_ (
    .A(_0286_),
    .B(_0287_),
    .C(_0321_),
    .X(_0323_)
  );
  sky130_fd_sc_hd__maj3_1 _0752_ (
    .A(_0283_),
    .B(_0284_),
    .C(_0323_),
    .X(_0324_)
  );
  sky130_fd_sc_hd__xnor2_1 _0753_ (
    .A(pid_integral[0]),
    .B(_0260_),
    .Y(_0325_)
  );
  sky130_fd_sc_hd__o211ai_1 _0754_ (
    .A1(_0218_),
    .A2(_0324_),
    .B1(_0325_),
    .C1(_0217_),
    .Y(_0326_)
  );
  sky130_fd_sc_hd__a21oi_1 _0755_ (
    .A1(_0218_),
    .A2(_0324_),
    .B1(_0085_),
    .Y(_0327_)
  );
  sky130_fd_sc_hd__a22o_1 _0756_ (
    .A1(dac_vco_tune[0]),
    .A2(_0085_),
    .B1(_0326_),
    .B2(_0327_),
    .X(_0031_)
  );
  sky130_fd_sc_hd__xor3_1 _0757_ (
    .A(_0307_),
    .B(_0308_),
    .C(_0309_),
    .X(_0328_)
  );
  sky130_fd_sc_hd__o211ai_1 _0758_ (
    .A1(_0218_),
    .A2(_0324_),
    .B1(_0328_),
    .C1(_0217_),
    .Y(_0329_)
  );
  sky130_fd_sc_hd__a22o_1 _0759_ (
    .A1(dac_vco_tune[1]),
    .A2(_0085_),
    .B1(_0327_),
    .B2(_0329_),
    .X(_0032_)
  );
  sky130_fd_sc_hd__and2_0 _0760_ (
    .A(_0310_),
    .B(_0311_),
    .X(_0330_)
  );
  sky130_fd_sc_hd__o221ai_1 _0761_ (
    .A1(_0218_),
    .A2(_0324_),
    .B1(_0330_),
    .B2(_0312_),
    .C1(_0217_),
    .Y(_0331_)
  );
  sky130_fd_sc_hd__a22o_1 _0762_ (
    .A1(dac_vco_tune[2]),
    .A2(_0085_),
    .B1(_0327_),
    .B2(_0331_),
    .X(_0033_)
  );
  sky130_fd_sc_hd__or3_1 _0763_ (
    .A(_0306_),
    .B(_0312_),
    .C(_0313_),
    .X(_0332_)
  );
  sky130_fd_sc_hd__nand2_1 _0764_ (
    .A(_0314_),
    .B(_0332_),
    .Y(_0333_)
  );
  sky130_fd_sc_hd__o211ai_1 _0765_ (
    .A1(_0218_),
    .A2(_0324_),
    .B1(_0333_),
    .C1(_0217_),
    .Y(_0334_)
  );
  sky130_fd_sc_hd__a22o_1 _0766_ (
    .A1(dac_vco_tune[3]),
    .A2(_0085_),
    .B1(_0327_),
    .B2(_0334_),
    .X(_0034_)
  );
  sky130_fd_sc_hd__xnor3_1 _0767_ (
    .A(_0298_),
    .B(_0300_),
    .C(_0315_),
    .X(_0335_)
  );
  sky130_fd_sc_hd__o211ai_1 _0768_ (
    .A1(_0218_),
    .A2(_0324_),
    .B1(_0335_),
    .C1(_0217_),
    .Y(_0336_)
  );
  sky130_fd_sc_hd__a22o_1 _0769_ (
    .A1(dac_vco_tune[4]),
    .A2(_0085_),
    .B1(_0327_),
    .B2(_0336_),
    .X(_0035_)
  );
  sky130_fd_sc_hd__nor2b_1 _0770_ (
    .A(_0296_),
    .B_N(_0317_),
    .Y(_0337_)
  );
  sky130_fd_sc_hd__xnor2_1 _0771_ (
    .A(_0316_),
    .B(_0337_),
    .Y(_0338_)
  );
  sky130_fd_sc_hd__o211ai_1 _0772_ (
    .A1(_0218_),
    .A2(_0324_),
    .B1(_0338_),
    .C1(_0217_),
    .Y(_0339_)
  );
  sky130_fd_sc_hd__a22o_1 _0773_ (
    .A1(dac_vco_tune[5]),
    .A2(_0085_),
    .B1(_0327_),
    .B2(_0339_),
    .X(_0036_)
  );
  sky130_fd_sc_hd__xnor2_1 _0774_ (
    .A(_0318_),
    .B(_0319_),
    .Y(_0340_)
  );
  sky130_fd_sc_hd__o211ai_1 _0775_ (
    .A1(_0218_),
    .A2(_0324_),
    .B1(_0340_),
    .C1(_0217_),
    .Y(_0341_)
  );
  sky130_fd_sc_hd__a22o_1 _0776_ (
    .A1(dac_vco_tune[6]),
    .A2(_0085_),
    .B1(_0327_),
    .B2(_0341_),
    .X(_0037_)
  );
  sky130_fd_sc_hd__xnor2_1 _0777_ (
    .A(_0290_),
    .B(_0320_),
    .Y(_0342_)
  );
  sky130_fd_sc_hd__o211ai_1 _0778_ (
    .A1(_0218_),
    .A2(_0324_),
    .B1(_0342_),
    .C1(_0217_),
    .Y(_0343_)
  );
  sky130_fd_sc_hd__a22o_1 _0779_ (
    .A1(dac_vco_tune[7]),
    .A2(_0085_),
    .B1(_0327_),
    .B2(_0343_),
    .X(_0038_)
  );
  sky130_fd_sc_hd__xnor2_1 _0780_ (
    .A(_0321_),
    .B(_0322_),
    .Y(_0344_)
  );
  sky130_fd_sc_hd__o211ai_1 _0781_ (
    .A1(_0218_),
    .A2(_0324_),
    .B1(_0344_),
    .C1(_0217_),
    .Y(_0345_)
  );
  sky130_fd_sc_hd__a22o_1 _0782_ (
    .A1(dac_vco_tune[8]),
    .A2(_0085_),
    .B1(_0327_),
    .B2(_0345_),
    .X(_0039_)
  );
  sky130_fd_sc_hd__xnor2_1 _0783_ (
    .A(_0285_),
    .B(_0323_),
    .Y(_0346_)
  );
  sky130_fd_sc_hd__o211ai_1 _0784_ (
    .A1(_0218_),
    .A2(_0324_),
    .B1(_0346_),
    .C1(_0217_),
    .Y(_0347_)
  );
  sky130_fd_sc_hd__a22o_1 _0785_ (
    .A1(dac_vco_tune[9]),
    .A2(_0085_),
    .B1(_0327_),
    .B2(_0347_),
    .X(_0040_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0786_ (
    .A(vco_counter[32]),
    .SLEEP(vco_bit32_d),
    .X(_0348_)
  );
  sky130_fd_sc_hd__nand2b_1 _0787_ (
    .A_N(vco_bit32_d),
    .B(vco_counter[32]),
    .Y(_0349_)
  );
  sky130_fd_sc_hd__xnor2_1 _0788_ (
    .A(count_1hz[0]),
    .B(_0349_),
    .Y(_0041_)
  );
  sky130_fd_sc_hd__and3_1 _0789_ (
    .A(count_1hz[0]),
    .B(count_1hz[1]),
    .C(_0348_),
    .X(_0350_)
  );
  sky130_fd_sc_hd__a21oi_1 _0790_ (
    .A1(count_1hz[0]),
    .A2(_0348_),
    .B1(count_1hz[1]),
    .Y(_0351_)
  );
  sky130_fd_sc_hd__nor2_1 _0791_ (
    .A(_0350_),
    .B(_0351_),
    .Y(_0042_)
  );
  sky130_fd_sc_hd__nor2_1 _0792_ (
    .A(count_1hz[2]),
    .B(_0350_),
    .Y(_0352_)
  );
  sky130_fd_sc_hd__nand3_1 _0793_ (
    .A(count_1hz[0]),
    .B(count_1hz[1]),
    .C(count_1hz[2]),
    .Y(_0353_)
  );
  sky130_fd_sc_hd__nor2_1 _0794_ (
    .A(_0349_),
    .B(_0353_),
    .Y(_0354_)
  );
  sky130_fd_sc_hd__nor2_1 _0795_ (
    .A(_0352_),
    .B(_0354_),
    .Y(_0043_)
  );
  sky130_fd_sc_hd__nor2_1 _0796_ (
    .A(count_1hz[3]),
    .B(_0354_),
    .Y(_0355_)
  );
  sky130_fd_sc_hd__nand4_1 _0797_ (
    .A(count_1hz[0]),
    .B(count_1hz[1]),
    .C(count_1hz[2]),
    .D(count_1hz[3]),
    .Y(_0356_)
  );
  sky130_fd_sc_hd__nor2_1 _0798_ (
    .A(_0349_),
    .B(_0356_),
    .Y(_0357_)
  );
  sky130_fd_sc_hd__nor2_1 _0799_ (
    .A(_0355_),
    .B(_0357_),
    .Y(_0044_)
  );
  sky130_fd_sc_hd__xor2_1 _0800_ (
    .A(count_1hz[4]),
    .B(_0357_),
    .X(_0045_)
  );
  sky130_fd_sc_hd__a21oi_1 _0801_ (
    .A1(count_1hz[4]),
    .A2(_0357_),
    .B1(count_1hz[5]),
    .Y(_0358_)
  );
  sky130_fd_sc_hd__nand2_1 _0802_ (
    .A(count_1hz[4]),
    .B(count_1hz[5]),
    .Y(_0359_)
  );
  sky130_fd_sc_hd__nor2_1 _0803_ (
    .A(_0356_),
    .B(_0359_),
    .Y(_0360_)
  );
  sky130_fd_sc_hd__nand2_1 _0804_ (
    .A(_0348_),
    .B(_0360_),
    .Y(_0361_)
  );
  sky130_fd_sc_hd__a21oi_1 _0805_ (
    .A1(_0348_),
    .A2(_0360_),
    .B1(_0358_),
    .Y(_0046_)
  );
  sky130_fd_sc_hd__xnor2_1 _0806_ (
    .A(count_1hz[6]),
    .B(_0361_),
    .Y(_0047_)
  );
  sky130_fd_sc_hd__a31oi_1 _0807_ (
    .A1(count_1hz[6]),
    .A2(_0348_),
    .A3(_0360_),
    .B1(count_1hz[7]),
    .Y(_0362_)
  );
  sky130_fd_sc_hd__and3_1 _0808_ (
    .A(count_1hz[6]),
    .B(count_1hz[7]),
    .C(_0360_),
    .X(_0363_)
  );
  sky130_fd_sc_hd__nand2_1 _0809_ (
    .A(_0348_),
    .B(_0363_),
    .Y(_0364_)
  );
  sky130_fd_sc_hd__a21oi_1 _0810_ (
    .A1(_0348_),
    .A2(_0363_),
    .B1(_0362_),
    .Y(_0048_)
  );
  sky130_fd_sc_hd__xnor2_1 _0811_ (
    .A(count_1hz[8]),
    .B(_0364_),
    .Y(_0049_)
  );
  sky130_fd_sc_hd__a31oi_1 _0812_ (
    .A1(count_1hz[8]),
    .A2(_0348_),
    .A3(_0363_),
    .B1(count_1hz[9]),
    .Y(_0365_)
  );
  sky130_fd_sc_hd__and3_1 _0813_ (
    .A(count_1hz[8]),
    .B(count_1hz[9]),
    .C(_0363_),
    .X(_0366_)
  );
  sky130_fd_sc_hd__nand2_1 _0814_ (
    .A(_0348_),
    .B(_0366_),
    .Y(_0367_)
  );
  sky130_fd_sc_hd__a21oi_1 _0815_ (
    .A1(_0348_),
    .A2(_0366_),
    .B1(_0365_),
    .Y(_0050_)
  );
  sky130_fd_sc_hd__xnor2_1 _0816_ (
    .A(count_1hz[10]),
    .B(_0367_),
    .Y(_0051_)
  );
  sky130_fd_sc_hd__a31oi_1 _0817_ (
    .A1(count_1hz[10]),
    .A2(_0348_),
    .A3(_0366_),
    .B1(count_1hz[11]),
    .Y(_0368_)
  );
  sky130_fd_sc_hd__nand3_1 _0818_ (
    .A(count_1hz[10]),
    .B(count_1hz[11]),
    .C(_0366_),
    .Y(_0369_)
  );
  sky130_fd_sc_hd__nand3_1 _0819_ (
    .A(count_1hz[10]),
    .B(count_1hz[11]),
    .C(_0366_),
    .Y(_0370_)
  );
  sky130_fd_sc_hd__nor2_1 _0820_ (
    .A(_0349_),
    .B(_0370_),
    .Y(_0371_)
  );
  sky130_fd_sc_hd__nor2_1 _0821_ (
    .A(_0368_),
    .B(_0371_),
    .Y(_0052_)
  );
  sky130_fd_sc_hd__xor2_1 _0822_ (
    .A(count_1hz[12]),
    .B(_0371_),
    .X(_0053_)
  );
  sky130_fd_sc_hd__a21oi_1 _0823_ (
    .A1(count_1hz[12]),
    .A2(_0371_),
    .B1(count_1hz[13]),
    .Y(_0372_)
  );
  sky130_fd_sc_hd__nand2_1 _0824_ (
    .A(count_1hz[12]),
    .B(count_1hz[13]),
    .Y(_0373_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0825_ (
    .A(_0370_),
    .SLEEP(_0373_),
    .X(_0374_)
  );
  sky130_fd_sc_hd__nor2_1 _0826_ (
    .A(_0349_),
    .B(_0374_),
    .Y(_0375_)
  );
  sky130_fd_sc_hd__nor2_1 _0827_ (
    .A(_0372_),
    .B(_0375_),
    .Y(_0054_)
  );
  sky130_fd_sc_hd__xor2_1 _0828_ (
    .A(count_1hz[14]),
    .B(_0375_),
    .X(_0055_)
  );
  sky130_fd_sc_hd__a21oi_1 _0829_ (
    .A1(count_1hz[14]),
    .A2(_0375_),
    .B1(count_1hz[15]),
    .Y(_0376_)
  );
  sky130_fd_sc_hd__nand2_1 _0830_ (
    .A(count_1hz[14]),
    .B(count_1hz[15]),
    .Y(_0377_)
  );
  sky130_fd_sc_hd__nor3_1 _0831_ (
    .A(_0349_),
    .B(_0374_),
    .C(_0377_),
    .Y(_0378_)
  );
  sky130_fd_sc_hd__nor2_1 _0832_ (
    .A(_0376_),
    .B(_0378_),
    .Y(_0056_)
  );
  sky130_fd_sc_hd__xor2_1 _0833_ (
    .A(count_1hz[16]),
    .B(_0378_),
    .X(_0057_)
  );
  sky130_fd_sc_hd__a21oi_1 _0834_ (
    .A1(count_1hz[16]),
    .A2(_0378_),
    .B1(count_1hz[17]),
    .Y(_0379_)
  );
  sky130_fd_sc_hd__nand2_1 _0835_ (
    .A(count_1hz[16]),
    .B(count_1hz[17]),
    .Y(_0380_)
  );
  sky130_fd_sc_hd__nor4_1 _0836_ (
    .A(_0369_),
    .B(_0373_),
    .C(_0377_),
    .D(_0380_),
    .Y(_0381_)
  );
  sky130_fd_sc_hd__nor4_1 _0837_ (
    .A(_0349_),
    .B(_0374_),
    .C(_0377_),
    .D(_0380_),
    .Y(_0382_)
  );
  sky130_fd_sc_hd__nor2_1 _0838_ (
    .A(_0379_),
    .B(_0382_),
    .Y(_0058_)
  );
  sky130_fd_sc_hd__xor2_1 _0839_ (
    .A(count_1hz[18]),
    .B(_0382_),
    .X(_0059_)
  );
  sky130_fd_sc_hd__a21oi_1 _0840_ (
    .A1(count_1hz[18]),
    .A2(_0382_),
    .B1(count_1hz[19]),
    .Y(_0383_)
  );
  sky130_fd_sc_hd__and4_1 _0841_ (
    .A(count_1hz[18]),
    .B(count_1hz[19]),
    .C(_0348_),
    .D(_0381_),
    .X(_0384_)
  );
  sky130_fd_sc_hd__nor2_1 _0842_ (
    .A(_0383_),
    .B(_0384_),
    .Y(_0060_)
  );
  sky130_fd_sc_hd__xor2_1 _0843_ (
    .A(count_1hz[20]),
    .B(_0384_),
    .X(_0061_)
  );
  sky130_fd_sc_hd__a21oi_1 _0844_ (
    .A1(count_1hz[20]),
    .A2(_0384_),
    .B1(count_1hz[21]),
    .Y(_0385_)
  );
  sky130_fd_sc_hd__a31oi_1 _0845_ (
    .A1(count_1hz[20]),
    .A2(count_1hz[21]),
    .A3(_0384_),
    .B1(_0385_),
    .Y(_0062_)
  );
  sky130_fd_sc_hd__a31oi_1 _0846_ (
    .A1(count_1hz[20]),
    .A2(count_1hz[21]),
    .A3(_0384_),
    .B1(count_1hz[22]),
    .Y(_0386_)
  );
  sky130_fd_sc_hd__and4_1 _0847_ (
    .A(count_1hz[20]),
    .B(count_1hz[21]),
    .C(count_1hz[22]),
    .D(_0384_),
    .X(_0387_)
  );
  sky130_fd_sc_hd__nor2_1 _0848_ (
    .A(_0386_),
    .B(_0387_),
    .Y(_0063_)
  );
  sky130_fd_sc_hd__nand2_1 _0849_ (
    .A(count_1hz[23]),
    .B(_0387_),
    .Y(_0388_)
  );
  sky130_fd_sc_hd__xor2_1 _0850_ (
    .A(count_1hz[23]),
    .B(_0387_),
    .X(_0064_)
  );
  sky130_fd_sc_hd__xnor2_1 _0851_ (
    .A(count_1hz[24]),
    .B(_0388_),
    .Y(_0065_)
  );
  sky130_fd_sc_hd__a31oi_1 _0852_ (
    .A1(count_1hz[23]),
    .A2(count_1hz[24]),
    .A3(_0387_),
    .B1(count_1hz[25]),
    .Y(_0389_)
  );
  sky130_fd_sc_hd__and4_1 _0853_ (
    .A(count_1hz[23]),
    .B(count_1hz[24]),
    .C(count_1hz[25]),
    .D(_0387_),
    .X(_0390_)
  );
  sky130_fd_sc_hd__nor2_1 _0854_ (
    .A(_0389_),
    .B(_0390_),
    .Y(_0066_)
  );
  sky130_fd_sc_hd__nand2_1 _0855_ (
    .A(count_1hz[26]),
    .B(_0390_),
    .Y(_0391_)
  );
  sky130_fd_sc_hd__xor2_1 _0856_ (
    .A(count_1hz[26]),
    .B(_0390_),
    .X(_0067_)
  );
  sky130_fd_sc_hd__xnor2_1 _0857_ (
    .A(count_1hz[27]),
    .B(_0391_),
    .Y(_0068_)
  );
  sky130_fd_sc_hd__a31oi_1 _0858_ (
    .A1(count_1hz[26]),
    .A2(count_1hz[27]),
    .A3(_0390_),
    .B1(count_1hz[28]),
    .Y(_0392_)
  );
  sky130_fd_sc_hd__and4_1 _0859_ (
    .A(count_1hz[26]),
    .B(count_1hz[27]),
    .C(count_1hz[28]),
    .D(_0390_),
    .X(_0393_)
  );
  sky130_fd_sc_hd__nor2_1 _0860_ (
    .A(_0392_),
    .B(_0393_),
    .Y(_0069_)
  );
  sky130_fd_sc_hd__xor2_1 _0861_ (
    .A(count_1hz[29]),
    .B(_0393_),
    .X(_0070_)
  );
  sky130_fd_sc_hd__a21oi_1 _0862_ (
    .A1(count_1hz[29]),
    .A2(_0393_),
    .B1(count_1hz[30]),
    .Y(_0394_)
  );
  sky130_fd_sc_hd__nand3_1 _0863_ (
    .A(count_1hz[29]),
    .B(count_1hz[30]),
    .C(_0393_),
    .Y(_0395_)
  );
  sky130_fd_sc_hd__nor2b_1 _0864_ (
    .A(_0394_),
    .B_N(_0395_),
    .Y(_0071_)
  );
  sky130_fd_sc_hd__xnor2_1 _0865_ (
    .A(count_1hz[31]),
    .B(_0395_),
    .Y(_0072_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0866_ (
    .A(spi_rx_valid),
    .SLEEP(spi_cs),
    .X(_0396_)
  );
  sky130_fd_sc_hd__mux2_1 _0867_ (
    .A0(spi_addr_latch[0]),
    .A1(spi_data_in[0]),
    .S(_0396_),
    .X(_0073_)
  );
  sky130_fd_sc_hd__mux2_1 _0868_ (
    .A0(spi_addr_latch[1]),
    .A1(spi_data_in[1]),
    .S(_0396_),
    .X(_0074_)
  );
  sky130_fd_sc_hd__mux2_1 _0869_ (
    .A0(spi_addr_latch[2]),
    .A1(spi_data_in[2]),
    .S(_0396_),
    .X(_0075_)
  );
  sky130_fd_sc_hd__mux2_1 _0870_ (
    .A0(spi_addr_latch[3]),
    .A1(spi_data_in[3]),
    .S(_0396_),
    .X(_0076_)
  );
  sky130_fd_sc_hd__mux2_1 _0871_ (
    .A0(spi_addr_latch[4]),
    .A1(spi_data_in[4]),
    .S(_0396_),
    .X(_0077_)
  );
  sky130_fd_sc_hd__mux2_1 _0872_ (
    .A0(spi_addr_latch[5]),
    .A1(spi_data_in[5]),
    .S(_0396_),
    .X(_0078_)
  );
  sky130_fd_sc_hd__mux2_1 _0873_ (
    .A0(spi_addr_latch[6]),
    .A1(spi_data_in[6]),
    .S(_0396_),
    .X(_0079_)
  );
  sky130_fd_sc_hd__mux2_1 _0874_ (
    .A0(spi_addr_latch[7]),
    .A1(spi_data_in[7]),
    .S(_0396_),
    .X(_0080_)
  );
  sky130_fd_sc_hd__or4_1 _0875_ (
    .A(spi_addr_latch[4]),
    .B(spi_addr_latch[5]),
    .C(spi_addr_latch[6]),
    .D(spi_addr_latch[7]),
    .X(_0397_)
  );
  sky130_fd_sc_hd__or3_1 _0876_ (
    .A(spi_addr_latch[2]),
    .B(spi_addr_latch[3]),
    .C(_0397_),
    .X(_0398_)
  );
  sky130_fd_sc_hd__nand2b_1 _0877_ (
    .A_N(spi_addr_latch[1]),
    .B(spi_addr_latch[0]),
    .Y(_0399_)
  );
  sky130_fd_sc_hd__nor2_1 _0878_ (
    .A(_0398_),
    .B(_0399_),
    .Y(_0400_)
  );
  sky130_fd_sc_hd__nand2_1 _0879_ (
    .A(spi_addr_latch[0]),
    .B(spi_addr_latch[1]),
    .Y(_0401_)
  );
  sky130_fd_sc_hd__nor2_1 _0880_ (
    .A(_0398_),
    .B(_0401_),
    .Y(_0402_)
  );
  sky130_fd_sc_hd__nand2b_1 _0881_ (
    .A_N(spi_addr_latch[0]),
    .B(spi_addr_latch[1]),
    .Y(_0403_)
  );
  sky130_fd_sc_hd__nor2_1 _0882_ (
    .A(_0398_),
    .B(_0403_),
    .Y(_0404_)
  );
  sky130_fd_sc_hd__nand2b_1 _0883_ (
    .A_N(spi_addr_latch[3]),
    .B(spi_addr_latch[2]),
    .Y(_0405_)
  );
  sky130_fd_sc_hd__nor3_1 _0884_ (
    .A(_0397_),
    .B(_0403_),
    .C(_0405_),
    .Y(_0406_)
  );
  sky130_fd_sc_hd__or3_1 _0885_ (
    .A(spi_addr_latch[0]),
    .B(spi_addr_latch[1]),
    .C(_0397_),
    .X(_0407_)
  );
  sky130_fd_sc_hd__nor3_1 _0886_ (
    .A(spi_addr_latch[2]),
    .B(spi_addr_latch[3]),
    .C(_0407_),
    .Y(_0408_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0887_ (
    .A(_0397_),
    .SLEEP(_0405_),
    .X(_0409_)
  );
  sky130_fd_sc_hd__nor2_1 _0888_ (
    .A(_0401_),
    .B(_0409_),
    .Y(_0410_)
  );
  sky130_fd_sc_hd__nor2_1 _0889_ (
    .A(_0399_),
    .B(_0409_),
    .Y(_0411_)
  );
  sky130_fd_sc_hd__nor2_1 _0890_ (
    .A(_0405_),
    .B(_0407_),
    .Y(_0412_)
  );
  sky130_fd_sc_hd__nor3b_1 _0891_ (
    .A(_0407_),
    .B(spi_addr_latch[2]),
    .C_N(spi_addr_latch[3]),
    .Y(_0413_)
  );
  sky130_fd_sc_hd__a22oi_1 _0892_ (
    .A1(count_1hz[8]),
    .A2(_0404_),
    .B1(_0408_),
    .B2(count_1hz[24]),
    .Y(_0414_)
  );
  sky130_fd_sc_hd__a22oi_1 _0893_ (
    .A1(count_1hz[16]),
    .A2(_0400_),
    .B1(_0413_),
    .B2(temp_adc[2]),
    .Y(_0415_)
  );
  sky130_fd_sc_hd__a22oi_1 _0894_ (
    .A1(count_1hz[0]),
    .A2(_0402_),
    .B1(_0412_),
    .B2(status_byte[0]),
    .Y(_0416_)
  );
  sky130_fd_sc_hd__a222oi_1 _0895_ (
    .A1(dac_heater_power[0]),
    .A2(_0406_),
    .B1(_0410_),
    .B2(photo_adc[0]),
    .C1(_0411_),
    .C2(dac_vco_tune[2]),
    .Y(_0417_)
  );
  sky130_fd_sc_hd__nand4_1 _0896_ (
    .A(_0414_),
    .B(_0415_),
    .C(_0416_),
    .D(_0417_),
    .Y(spi_data_out[0])
  );
  sky130_fd_sc_hd__a22oi_1 _0897_ (
    .A1(count_1hz[9]),
    .A2(_0404_),
    .B1(_0408_),
    .B2(count_1hz[25]),
    .Y(_0418_)
  );
  sky130_fd_sc_hd__a22oi_1 _0898_ (
    .A1(count_1hz[17]),
    .A2(_0400_),
    .B1(_0413_),
    .B2(temp_adc[3]),
    .Y(_0419_)
  );
  sky130_fd_sc_hd__a22oi_1 _0899_ (
    .A1(count_1hz[1]),
    .A2(_0402_),
    .B1(_0412_),
    .B2(status_byte[1]),
    .Y(_0420_)
  );
  sky130_fd_sc_hd__a222oi_1 _0900_ (
    .A1(dac_heater_power[1]),
    .A2(_0406_),
    .B1(_0410_),
    .B2(photo_adc[1]),
    .C1(_0411_),
    .C2(dac_vco_tune[3]),
    .Y(_0421_)
  );
  sky130_fd_sc_hd__nand4_1 _0901_ (
    .A(_0418_),
    .B(_0419_),
    .C(_0420_),
    .D(_0421_),
    .Y(spi_data_out[1])
  );
  sky130_fd_sc_hd__a22oi_1 _0902_ (
    .A1(count_1hz[10]),
    .A2(_0404_),
    .B1(_0408_),
    .B2(count_1hz[26]),
    .Y(_0422_)
  );
  sky130_fd_sc_hd__a22oi_1 _0903_ (
    .A1(count_1hz[18]),
    .A2(_0400_),
    .B1(_0413_),
    .B2(temp_adc[4]),
    .Y(_0423_)
  );
  sky130_fd_sc_hd__a22oi_1 _0904_ (
    .A1(count_1hz[2]),
    .A2(_0402_),
    .B1(_0412_),
    .B2(status_byte[2]),
    .Y(_0424_)
  );
  sky130_fd_sc_hd__a222oi_1 _0905_ (
    .A1(dac_heater_power[2]),
    .A2(_0406_),
    .B1(_0410_),
    .B2(photo_adc[2]),
    .C1(_0411_),
    .C2(dac_vco_tune[4]),
    .Y(_0425_)
  );
  sky130_fd_sc_hd__nand4_1 _0906_ (
    .A(_0422_),
    .B(_0423_),
    .C(_0424_),
    .D(_0425_),
    .Y(spi_data_out[2])
  );
  sky130_fd_sc_hd__a22oi_1 _0907_ (
    .A1(count_1hz[11]),
    .A2(_0404_),
    .B1(_0408_),
    .B2(count_1hz[27]),
    .Y(_0426_)
  );
  sky130_fd_sc_hd__a22oi_1 _0908_ (
    .A1(count_1hz[19]),
    .A2(_0400_),
    .B1(_0413_),
    .B2(temp_adc[5]),
    .Y(_0427_)
  );
  sky130_fd_sc_hd__a22oi_1 _0909_ (
    .A1(count_1hz[3]),
    .A2(_0402_),
    .B1(_0412_),
    .B2(status_byte[3]),
    .Y(_0428_)
  );
  sky130_fd_sc_hd__a222oi_1 _0910_ (
    .A1(dac_heater_power[3]),
    .A2(_0406_),
    .B1(_0410_),
    .B2(photo_adc[3]),
    .C1(_0411_),
    .C2(dac_vco_tune[5]),
    .Y(_0429_)
  );
  sky130_fd_sc_hd__nand4_1 _0911_ (
    .A(_0426_),
    .B(_0427_),
    .C(_0428_),
    .D(_0429_),
    .Y(spi_data_out[3])
  );
  sky130_fd_sc_hd__a22oi_1 _0912_ (
    .A1(count_1hz[12]),
    .A2(_0404_),
    .B1(_0408_),
    .B2(count_1hz[28]),
    .Y(_0430_)
  );
  sky130_fd_sc_hd__a22oi_1 _0913_ (
    .A1(count_1hz[20]),
    .A2(_0400_),
    .B1(_0413_),
    .B2(temp_adc[6]),
    .Y(_0431_)
  );
  sky130_fd_sc_hd__a22oi_1 _0914_ (
    .A1(count_1hz[4]),
    .A2(_0402_),
    .B1(_0412_),
    .B2(status_byte[4]),
    .Y(_0432_)
  );
  sky130_fd_sc_hd__a222oi_1 _0915_ (
    .A1(dac_heater_power[4]),
    .A2(_0406_),
    .B1(_0410_),
    .B2(photo_adc[4]),
    .C1(_0411_),
    .C2(dac_vco_tune[6]),
    .Y(_0433_)
  );
  sky130_fd_sc_hd__nand4_1 _0916_ (
    .A(_0430_),
    .B(_0431_),
    .C(_0432_),
    .D(_0433_),
    .Y(spi_data_out[4])
  );
  sky130_fd_sc_hd__a222oi_1 _0917_ (
    .A1(count_1hz[5]),
    .A2(_0402_),
    .B1(_0404_),
    .B2(count_1hz[13]),
    .C1(_0413_),
    .C2(temp_adc[7]),
    .Y(_0434_)
  );
  sky130_fd_sc_hd__a222oi_1 _0918_ (
    .A1(dac_heater_power[5]),
    .A2(_0406_),
    .B1(_0410_),
    .B2(photo_adc[5]),
    .C1(_0411_),
    .C2(dac_vco_tune[7]),
    .Y(_0435_)
  );
  sky130_fd_sc_hd__a22oi_1 _0919_ (
    .A1(count_1hz[21]),
    .A2(_0400_),
    .B1(_0408_),
    .B2(count_1hz[29]),
    .Y(_0436_)
  );
  sky130_fd_sc_hd__nand3_1 _0920_ (
    .A(_0434_),
    .B(_0435_),
    .C(_0436_),
    .Y(spi_data_out[5])
  );
  sky130_fd_sc_hd__a222oi_1 _0921_ (
    .A1(count_1hz[6]),
    .A2(_0402_),
    .B1(_0404_),
    .B2(count_1hz[14]),
    .C1(_0413_),
    .C2(temp_adc[8]),
    .Y(_0437_)
  );
  sky130_fd_sc_hd__a222oi_1 _0922_ (
    .A1(dac_heater_power[6]),
    .A2(_0406_),
    .B1(_0410_),
    .B2(photo_adc[6]),
    .C1(_0411_),
    .C2(dac_vco_tune[8]),
    .Y(_0438_)
  );
  sky130_fd_sc_hd__a22oi_1 _0923_ (
    .A1(count_1hz[22]),
    .A2(_0400_),
    .B1(_0408_),
    .B2(count_1hz[30]),
    .Y(_0439_)
  );
  sky130_fd_sc_hd__nand3_1 _0924_ (
    .A(_0437_),
    .B(_0438_),
    .C(_0439_),
    .Y(spi_data_out[6])
  );
  sky130_fd_sc_hd__a22oi_1 _0925_ (
    .A1(count_1hz[15]),
    .A2(_0404_),
    .B1(_0408_),
    .B2(count_1hz[31]),
    .Y(_0440_)
  );
  sky130_fd_sc_hd__a22oi_1 _0926_ (
    .A1(count_1hz[23]),
    .A2(_0400_),
    .B1(_0413_),
    .B2(temp_adc[9]),
    .Y(_0441_)
  );
  sky130_fd_sc_hd__a22oi_1 _0927_ (
    .A1(count_1hz[7]),
    .A2(_0402_),
    .B1(_0412_),
    .B2(status_byte[7]),
    .Y(_0442_)
  );
  sky130_fd_sc_hd__a222oi_1 _0928_ (
    .A1(dac_heater_power[7]),
    .A2(_0406_),
    .B1(_0410_),
    .B2(photo_adc[7]),
    .C1(_0411_),
    .C2(dac_vco_tune[9]),
    .Y(_0443_)
  );
  sky130_fd_sc_hd__nand4_1 _0929_ (
    .A(_0440_),
    .B(_0441_),
    .C(_0442_),
    .D(_0443_),
    .Y(spi_data_out[7])
  );
  sky130_fd_sc_hd__nand2_1 _0930_ (
    .A(vco_counter[0]),
    .B(vco_counter[1]),
    .Y(_0444_)
  );
  sky130_fd_sc_hd__xor2_1 _0931_ (
    .A(vco_counter[0]),
    .B(vco_counter[1]),
    .X(_0476_[1])
  );
  sky130_fd_sc_hd__xnor2_1 _0932_ (
    .A(vco_counter[2]),
    .B(_0444_),
    .Y(_0476_[2])
  );
  sky130_fd_sc_hd__nand4_1 _0933_ (
    .A(vco_counter[0]),
    .B(vco_counter[1]),
    .C(vco_counter[2]),
    .D(vco_counter[3]),
    .Y(_0445_)
  );
  sky130_fd_sc_hd__a31oi_1 _0934_ (
    .A1(vco_counter[0]),
    .A2(vco_counter[1]),
    .A3(vco_counter[2]),
    .B1(vco_counter[3]),
    .Y(_0446_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0935_ (
    .A(_0445_),
    .SLEEP(_0446_),
    .X(_0476_[3])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0936_ (
    .A(vco_counter[4]),
    .SLEEP(_0445_),
    .X(_0447_)
  );
  sky130_fd_sc_hd__xnor2_1 _0937_ (
    .A(vco_counter[4]),
    .B(_0445_),
    .Y(_0476_[4])
  );
  sky130_fd_sc_hd__xor2_1 _0938_ (
    .A(vco_counter[5]),
    .B(_0447_),
    .X(_0476_[5])
  );
  sky130_fd_sc_hd__nand3_1 _0939_ (
    .A(vco_counter[5]),
    .B(vco_counter[6]),
    .C(_0447_),
    .Y(_0448_)
  );
  sky130_fd_sc_hd__a21oi_1 _0940_ (
    .A1(vco_counter[5]),
    .A2(_0447_),
    .B1(vco_counter[6]),
    .Y(_0449_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0941_ (
    .A(_0448_),
    .SLEEP(_0449_),
    .X(_0476_[6])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0942_ (
    .A(vco_counter[7]),
    .SLEEP(_0448_),
    .X(_0450_)
  );
  sky130_fd_sc_hd__xnor2_1 _0943_ (
    .A(vco_counter[7]),
    .B(_0448_),
    .Y(_0476_[7])
  );
  sky130_fd_sc_hd__xor2_1 _0944_ (
    .A(vco_counter[8]),
    .B(_0450_),
    .X(_0476_[8])
  );
  sky130_fd_sc_hd__nand3_1 _0945_ (
    .A(vco_counter[8]),
    .B(vco_counter[9]),
    .C(_0450_),
    .Y(_0451_)
  );
  sky130_fd_sc_hd__a21oi_1 _0946_ (
    .A1(vco_counter[8]),
    .A2(_0450_),
    .B1(vco_counter[9]),
    .Y(_0452_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0947_ (
    .A(_0451_),
    .SLEEP(_0452_),
    .X(_0476_[9])
  );
  sky130_fd_sc_hd__and4_1 _0948_ (
    .A(vco_counter[8]),
    .B(vco_counter[9]),
    .C(vco_counter[10]),
    .D(_0450_),
    .X(_0453_)
  );
  sky130_fd_sc_hd__xnor2_1 _0949_ (
    .A(vco_counter[10]),
    .B(_0451_),
    .Y(_0476_[10])
  );
  sky130_fd_sc_hd__nand2_1 _0950_ (
    .A(vco_counter[11]),
    .B(_0453_),
    .Y(_0454_)
  );
  sky130_fd_sc_hd__xor2_1 _0951_ (
    .A(vco_counter[11]),
    .B(_0453_),
    .X(_0476_[11])
  );
  sky130_fd_sc_hd__xnor2_1 _0952_ (
    .A(vco_counter[12]),
    .B(_0454_),
    .Y(_0476_[12])
  );
  sky130_fd_sc_hd__and4_1 _0953_ (
    .A(vco_counter[11]),
    .B(vco_counter[12]),
    .C(vco_counter[13]),
    .D(_0453_),
    .X(_0455_)
  );
  sky130_fd_sc_hd__a31oi_1 _0954_ (
    .A1(vco_counter[11]),
    .A2(vco_counter[12]),
    .A3(_0453_),
    .B1(vco_counter[13]),
    .Y(_0456_)
  );
  sky130_fd_sc_hd__nor2_1 _0955_ (
    .A(_0455_),
    .B(_0456_),
    .Y(_0476_[13])
  );
  sky130_fd_sc_hd__nand2_1 _0956_ (
    .A(vco_counter[14]),
    .B(_0455_),
    .Y(_0457_)
  );
  sky130_fd_sc_hd__xor2_1 _0957_ (
    .A(vco_counter[14]),
    .B(_0455_),
    .X(_0476_[14])
  );
  sky130_fd_sc_hd__xnor2_1 _0958_ (
    .A(vco_counter[15]),
    .B(_0457_),
    .Y(_0476_[15])
  );
  sky130_fd_sc_hd__and4_1 _0959_ (
    .A(vco_counter[14]),
    .B(vco_counter[15]),
    .C(vco_counter[16]),
    .D(_0455_),
    .X(_0458_)
  );
  sky130_fd_sc_hd__a31oi_1 _0960_ (
    .A1(vco_counter[14]),
    .A2(vco_counter[15]),
    .A3(_0455_),
    .B1(vco_counter[16]),
    .Y(_0459_)
  );
  sky130_fd_sc_hd__nor2_1 _0961_ (
    .A(_0458_),
    .B(_0459_),
    .Y(_0476_[16])
  );
  sky130_fd_sc_hd__xor2_1 _0962_ (
    .A(vco_counter[17]),
    .B(_0458_),
    .X(_0476_[17])
  );
  sky130_fd_sc_hd__nand3_1 _0963_ (
    .A(vco_counter[17]),
    .B(vco_counter[18]),
    .C(_0458_),
    .Y(_0460_)
  );
  sky130_fd_sc_hd__a21oi_1 _0964_ (
    .A1(vco_counter[17]),
    .A2(_0458_),
    .B1(vco_counter[18]),
    .Y(_0461_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0965_ (
    .A(_0460_),
    .SLEEP(_0461_),
    .X(_0476_[18])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0966_ (
    .A(vco_counter[19]),
    .SLEEP(_0460_),
    .X(_0462_)
  );
  sky130_fd_sc_hd__xnor2_1 _0967_ (
    .A(vco_counter[19]),
    .B(_0460_),
    .Y(_0476_[19])
  );
  sky130_fd_sc_hd__xor2_1 _0968_ (
    .A(vco_counter[20]),
    .B(_0462_),
    .X(_0476_[20])
  );
  sky130_fd_sc_hd__nand3_1 _0969_ (
    .A(vco_counter[20]),
    .B(vco_counter[21]),
    .C(_0462_),
    .Y(_0463_)
  );
  sky130_fd_sc_hd__a21oi_1 _0970_ (
    .A1(vco_counter[20]),
    .A2(_0462_),
    .B1(vco_counter[21]),
    .Y(_0464_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0971_ (
    .A(_0463_),
    .SLEEP(_0464_),
    .X(_0476_[21])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0972_ (
    .A(vco_counter[22]),
    .SLEEP(_0463_),
    .X(_0465_)
  );
  sky130_fd_sc_hd__xnor2_1 _0973_ (
    .A(vco_counter[22]),
    .B(_0463_),
    .Y(_0476_[22])
  );
  sky130_fd_sc_hd__xor2_1 _0974_ (
    .A(vco_counter[23]),
    .B(_0465_),
    .X(_0476_[23])
  );
  sky130_fd_sc_hd__nand3_1 _0975_ (
    .A(vco_counter[23]),
    .B(vco_counter[24]),
    .C(_0465_),
    .Y(_0466_)
  );
  sky130_fd_sc_hd__a21oi_1 _0976_ (
    .A1(vco_counter[23]),
    .A2(_0465_),
    .B1(vco_counter[24]),
    .Y(_0467_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0977_ (
    .A(_0466_),
    .SLEEP(_0467_),
    .X(_0476_[24])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0978_ (
    .A(vco_counter[25]),
    .SLEEP(_0466_),
    .X(_0468_)
  );
  sky130_fd_sc_hd__xnor2_1 _0979_ (
    .A(vco_counter[25]),
    .B(_0466_),
    .Y(_0476_[25])
  );
  sky130_fd_sc_hd__xor2_1 _0980_ (
    .A(status_byte[4]),
    .B(_0468_),
    .X(_0476_[26])
  );
  sky130_fd_sc_hd__nand3_1 _0981_ (
    .A(status_byte[4]),
    .B(vco_counter[27]),
    .C(_0468_),
    .Y(_0469_)
  );
  sky130_fd_sc_hd__a21oi_1 _0982_ (
    .A1(status_byte[4]),
    .A2(_0468_),
    .B1(vco_counter[27]),
    .Y(_0470_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0983_ (
    .A(_0469_),
    .SLEEP(_0470_),
    .X(_0476_[27])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0984_ (
    .A(vco_counter[28]),
    .SLEEP(_0469_),
    .X(_0471_)
  );
  sky130_fd_sc_hd__xnor2_1 _0985_ (
    .A(vco_counter[28]),
    .B(_0469_),
    .Y(_0476_[28])
  );
  sky130_fd_sc_hd__nand2_1 _0986_ (
    .A(vco_counter[29]),
    .B(_0471_),
    .Y(_0472_)
  );
  sky130_fd_sc_hd__xor2_1 _0987_ (
    .A(vco_counter[29]),
    .B(_0471_),
    .X(_0476_[29])
  );
  sky130_fd_sc_hd__xnor2_1 _0988_ (
    .A(vco_counter[30]),
    .B(_0472_),
    .Y(_0476_[30])
  );
  sky130_fd_sc_hd__nand4_1 _0989_ (
    .A(vco_counter[29]),
    .B(vco_counter[30]),
    .C(vco_counter[31]),
    .D(_0471_),
    .Y(_0473_)
  );
  sky130_fd_sc_hd__a31oi_1 _0990_ (
    .A1(vco_counter[29]),
    .A2(vco_counter[30]),
    .A3(_0471_),
    .B1(vco_counter[31]),
    .Y(_0474_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0991_ (
    .A(_0473_),
    .SLEEP(_0474_),
    .X(_0476_[31])
  );
  sky130_fd_sc_hd__xnor2_1 _0992_ (
    .A(vco_counter[32]),
    .B(_0473_),
    .Y(_0476_[32])
  );
  sky130_fd_sc_hd__dfrtp_1 _0993_ (
    .CLK(clk_vco),
    .D(_0000_),
    .Q(status_byte[7]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0994_ (
    .CLK(clk_vco),
    .D(_0001_),
    .Q(dac_heater_power[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0995_ (
    .CLK(clk_vco),
    .D(_0002_),
    .Q(dac_heater_power[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0996_ (
    .CLK(clk_vco),
    .D(_0003_),
    .Q(dac_heater_power[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0997_ (
    .CLK(clk_vco),
    .D(_0004_),
    .Q(dac_heater_power[3]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0998_ (
    .CLK(clk_vco),
    .D(_0005_),
    .Q(dac_heater_power[4]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _0999_ (
    .CLK(clk_vco),
    .D(_0006_),
    .Q(dac_heater_power[5]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1000_ (
    .CLK(clk_vco),
    .D(_0007_),
    .Q(dac_heater_power[6]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1001_ (
    .CLK(clk_vco),
    .D(_0008_),
    .Q(dac_heater_power[7]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1002_ (
    .CLK(clk_vco),
    .D(_0009_),
    .Q(lock_counter[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1003_ (
    .CLK(clk_vco),
    .D(_0010_),
    .Q(lock_counter[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1004_ (
    .CLK(clk_vco),
    .D(_0011_),
    .Q(lock_counter[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1005_ (
    .CLK(clk_vco),
    .D(_0012_),
    .Q(lock_counter[3]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1006_ (
    .CLK(clk_vco),
    .D(_0013_),
    .Q(pid_integral[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1007_ (
    .CLK(clk_vco),
    .D(_0014_),
    .Q(pid_integral[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1008_ (
    .CLK(clk_vco),
    .D(_0015_),
    .Q(pid_integral[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1009_ (
    .CLK(clk_vco),
    .D(_0016_),
    .Q(pid_integral[3]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1010_ (
    .CLK(clk_vco),
    .D(_0017_),
    .Q(pid_integral[4]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1011_ (
    .CLK(clk_vco),
    .D(_0018_),
    .Q(pid_integral[5]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1012_ (
    .CLK(clk_vco),
    .D(_0019_),
    .Q(status_byte[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1013_ (
    .CLK(clk_vco),
    .D(_0020_),
    .Q(status_byte[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1014_ (
    .CLK(clk_vco),
    .D(_0021_),
    .Q(status_byte[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1015_ (
    .CLK(clk_vco),
    .D(_0022_),
    .Q(status_byte[3]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1016_ (
    .CLK(clk_vco),
    .D(_0023_),
    .Q(pid_last_error[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1017_ (
    .CLK(clk_vco),
    .D(_0024_),
    .Q(pid_last_error[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1018_ (
    .CLK(clk_vco),
    .D(_0025_),
    .Q(pid_last_error[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1019_ (
    .CLK(clk_vco),
    .D(_0026_),
    .Q(pid_last_error[3]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1020_ (
    .CLK(clk_vco),
    .D(_0027_),
    .Q(pid_last_error[4]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1021_ (
    .CLK(clk_vco),
    .D(_0028_),
    .Q(pid_last_error[5]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1022_ (
    .CLK(clk_vco),
    .D(_0029_),
    .Q(pid_last_error[6]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1023_ (
    .CLK(clk_vco),
    .D(_0030_),
    .Q(pid_last_error[7]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1024_ (
    .CLK(clk_vco),
    .D(_0031_),
    .Q(dac_vco_tune[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1025_ (
    .CLK(clk_vco),
    .D(_0032_),
    .Q(dac_vco_tune[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1026_ (
    .CLK(clk_vco),
    .D(_0033_),
    .Q(dac_vco_tune[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1027_ (
    .CLK(clk_vco),
    .D(_0034_),
    .Q(dac_vco_tune[3]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1028_ (
    .CLK(clk_vco),
    .D(_0035_),
    .Q(dac_vco_tune[4]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1029_ (
    .CLK(clk_vco),
    .D(_0036_),
    .Q(dac_vco_tune[5]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1030_ (
    .CLK(clk_vco),
    .D(_0037_),
    .Q(dac_vco_tune[6]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1031_ (
    .CLK(clk_vco),
    .D(_0038_),
    .Q(dac_vco_tune[7]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1032_ (
    .CLK(clk_vco),
    .D(_0039_),
    .Q(dac_vco_tune[8]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfstp_2 _1033_ (
    .CLK(clk_vco),
    .D(_0040_),
    .Q(dac_vco_tune[9]),
    .SET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1034_ (
    .CLK(clk_vco),
    .D(_0041_),
    .Q(count_1hz[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1035_ (
    .CLK(clk_vco),
    .D(_0042_),
    .Q(count_1hz[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1036_ (
    .CLK(clk_vco),
    .D(_0043_),
    .Q(count_1hz[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1037_ (
    .CLK(clk_vco),
    .D(_0044_),
    .Q(count_1hz[3]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1038_ (
    .CLK(clk_vco),
    .D(_0045_),
    .Q(count_1hz[4]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1039_ (
    .CLK(clk_vco),
    .D(_0046_),
    .Q(count_1hz[5]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1040_ (
    .CLK(clk_vco),
    .D(_0047_),
    .Q(count_1hz[6]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1041_ (
    .CLK(clk_vco),
    .D(_0048_),
    .Q(count_1hz[7]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1042_ (
    .CLK(clk_vco),
    .D(_0049_),
    .Q(count_1hz[8]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1043_ (
    .CLK(clk_vco),
    .D(_0050_),
    .Q(count_1hz[9]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1044_ (
    .CLK(clk_vco),
    .D(_0051_),
    .Q(count_1hz[10]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1045_ (
    .CLK(clk_vco),
    .D(_0052_),
    .Q(count_1hz[11]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1046_ (
    .CLK(clk_vco),
    .D(_0053_),
    .Q(count_1hz[12]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1047_ (
    .CLK(clk_vco),
    .D(_0054_),
    .Q(count_1hz[13]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1048_ (
    .CLK(clk_vco),
    .D(_0055_),
    .Q(count_1hz[14]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1049_ (
    .CLK(clk_vco),
    .D(_0056_),
    .Q(count_1hz[15]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1050_ (
    .CLK(clk_vco),
    .D(_0057_),
    .Q(count_1hz[16]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1051_ (
    .CLK(clk_vco),
    .D(_0058_),
    .Q(count_1hz[17]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1052_ (
    .CLK(clk_vco),
    .D(_0059_),
    .Q(count_1hz[18]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1053_ (
    .CLK(clk_vco),
    .D(_0060_),
    .Q(count_1hz[19]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1054_ (
    .CLK(clk_vco),
    .D(_0061_),
    .Q(count_1hz[20]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1055_ (
    .CLK(clk_vco),
    .D(_0062_),
    .Q(count_1hz[21]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1056_ (
    .CLK(clk_vco),
    .D(_0063_),
    .Q(count_1hz[22]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1057_ (
    .CLK(clk_vco),
    .D(_0064_),
    .Q(count_1hz[23]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1058_ (
    .CLK(clk_vco),
    .D(_0065_),
    .Q(count_1hz[24]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1059_ (
    .CLK(clk_vco),
    .D(_0066_),
    .Q(count_1hz[25]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1060_ (
    .CLK(clk_vco),
    .D(_0067_),
    .Q(count_1hz[26]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1061_ (
    .CLK(clk_vco),
    .D(_0068_),
    .Q(count_1hz[27]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1062_ (
    .CLK(clk_vco),
    .D(_0069_),
    .Q(count_1hz[28]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1063_ (
    .CLK(clk_vco),
    .D(_0070_),
    .Q(count_1hz[29]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1064_ (
    .CLK(clk_vco),
    .D(_0071_),
    .Q(count_1hz[30]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1065_ (
    .CLK(clk_vco),
    .D(_0072_),
    .Q(count_1hz[31]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1066_ (
    .CLK(spi_clk),
    .D(_0073_),
    .Q(spi_addr_latch[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1067_ (
    .CLK(spi_clk),
    .D(_0074_),
    .Q(spi_addr_latch[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1068_ (
    .CLK(spi_clk),
    .D(_0075_),
    .Q(spi_addr_latch[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1069_ (
    .CLK(spi_clk),
    .D(_0076_),
    .Q(spi_addr_latch[3]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1070_ (
    .CLK(spi_clk),
    .D(_0077_),
    .Q(spi_addr_latch[4]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1071_ (
    .CLK(spi_clk),
    .D(_0078_),
    .Q(spi_addr_latch[5]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1072_ (
    .CLK(spi_clk),
    .D(_0079_),
    .Q(spi_addr_latch[6]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1073_ (
    .CLK(spi_clk),
    .D(_0080_),
    .Q(spi_addr_latch[7]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1074_ (
    .CLK(clk_vco),
    .D(status_byte[4]),
    .Q(vco_bit26_d),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1075_ (
    .CLK(clk_vco),
    .D(vco_counter[32]),
    .Q(vco_bit32_d),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1076_ (
    .CLK(clk_vco),
    .D(_0475_[0]),
    .Q(vco_counter[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1077_ (
    .CLK(clk_vco),
    .D(_0476_[1]),
    .Q(vco_counter[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1078_ (
    .CLK(clk_vco),
    .D(_0476_[2]),
    .Q(vco_counter[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1079_ (
    .CLK(clk_vco),
    .D(_0476_[3]),
    .Q(vco_counter[3]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1080_ (
    .CLK(clk_vco),
    .D(_0476_[4]),
    .Q(vco_counter[4]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1081_ (
    .CLK(clk_vco),
    .D(_0476_[5]),
    .Q(vco_counter[5]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1082_ (
    .CLK(clk_vco),
    .D(_0476_[6]),
    .Q(vco_counter[6]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1083_ (
    .CLK(clk_vco),
    .D(_0476_[7]),
    .Q(vco_counter[7]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1084_ (
    .CLK(clk_vco),
    .D(_0476_[8]),
    .Q(vco_counter[8]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1085_ (
    .CLK(clk_vco),
    .D(_0476_[9]),
    .Q(vco_counter[9]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1086_ (
    .CLK(clk_vco),
    .D(_0476_[10]),
    .Q(vco_counter[10]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1087_ (
    .CLK(clk_vco),
    .D(_0476_[11]),
    .Q(vco_counter[11]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1088_ (
    .CLK(clk_vco),
    .D(_0476_[12]),
    .Q(vco_counter[12]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1089_ (
    .CLK(clk_vco),
    .D(_0476_[13]),
    .Q(vco_counter[13]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1090_ (
    .CLK(clk_vco),
    .D(_0476_[14]),
    .Q(vco_counter[14]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1091_ (
    .CLK(clk_vco),
    .D(_0476_[15]),
    .Q(vco_counter[15]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1092_ (
    .CLK(clk_vco),
    .D(_0476_[16]),
    .Q(vco_counter[16]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1093_ (
    .CLK(clk_vco),
    .D(_0476_[17]),
    .Q(vco_counter[17]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1094_ (
    .CLK(clk_vco),
    .D(_0476_[18]),
    .Q(vco_counter[18]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1095_ (
    .CLK(clk_vco),
    .D(_0476_[19]),
    .Q(vco_counter[19]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1096_ (
    .CLK(clk_vco),
    .D(_0476_[20]),
    .Q(vco_counter[20]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1097_ (
    .CLK(clk_vco),
    .D(_0476_[21]),
    .Q(vco_counter[21]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1098_ (
    .CLK(clk_vco),
    .D(_0476_[22]),
    .Q(vco_counter[22]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1099_ (
    .CLK(clk_vco),
    .D(_0476_[23]),
    .Q(vco_counter[23]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1100_ (
    .CLK(clk_vco),
    .D(_0476_[24]),
    .Q(vco_counter[24]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1101_ (
    .CLK(clk_vco),
    .D(_0476_[25]),
    .Q(vco_counter[25]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1102_ (
    .CLK(clk_vco),
    .D(_0476_[26]),
    .Q(status_byte[4]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1103_ (
    .CLK(clk_vco),
    .D(_0476_[27]),
    .Q(vco_counter[27]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1104_ (
    .CLK(clk_vco),
    .D(_0476_[28]),
    .Q(vco_counter[28]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1105_ (
    .CLK(clk_vco),
    .D(_0476_[29]),
    .Q(vco_counter[29]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1106_ (
    .CLK(clk_vco),
    .D(_0476_[30]),
    .Q(vco_counter[30]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1107_ (
    .CLK(clk_vco),
    .D(_0476_[31]),
    .Q(vco_counter[31]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1108_ (
    .CLK(clk_vco),
    .D(_0476_[32]),
    .Q(vco_counter[32]),
    .RESET_B(reset_n)
  );
  spi_slave spi_inst (
    .cs_n(spi_cs),
    .data_in(spi_data_out),
    .data_out(spi_data_in),
    .miso(spi_miso),
    .mosi(spi_mosi),
    .reset_n(reset_n),
    .rx_valid(spi_rx_valid),
    .sclk(spi_clk)
  );
  assign _0475_[32:1] = { vco_counter[32:27], status_byte[4], vco_counter[25:1] };
  assign _0476_[0] = _0475_[0];
  assign pid_integral[9:6] = status_byte[3:0];
  assign status_byte[6:5] = 2'h0;
  assign valid_lock = status_byte[7];
  assign vco_counter[26] = status_byte[4];
endmodule

module spi_slave(sclk, mosi, miso, cs_n, reset_n, data_in, data_out, rx_valid);
  wire [2:0] _00_;
  wire [7:0] _01_;
  wire [7:0] _02_;
  wire _03_;
  wire _04_;
  wire [2:0] bit_count;
  input cs_n;
  wire cs_n;
  input [7:0] data_in;
  wire [7:0] data_in;
  output [7:0] data_out;
  wire [7:0] data_out;
  output miso;
  wire miso;
  input mosi;
  wire mosi;
  input reset_n;
  wire reset_n;
  output rx_valid;
  wire rx_valid;
  input sclk;
  wire sclk;
  wire [7:0] tx_shift;
  sky130_fd_sc_hd__and3_1 _05_ (
    .A(bit_count[0]),
    .B(bit_count[2]),
    .C(bit_count[1]),
    .X(rx_valid)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _06_ (
    .A(mosi),
    .SLEEP(cs_n),
    .X(_01_[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _07_ (
    .A(data_out[0]),
    .SLEEP(cs_n),
    .X(_01_[1])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _08_ (
    .A(data_out[1]),
    .SLEEP(cs_n),
    .X(_01_[2])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _09_ (
    .A(data_out[2]),
    .SLEEP(cs_n),
    .X(_01_[3])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _10_ (
    .A(data_out[3]),
    .SLEEP(cs_n),
    .X(_01_[4])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _11_ (
    .A(data_out[4]),
    .SLEEP(cs_n),
    .X(_01_[5])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _12_ (
    .A(data_out[5]),
    .SLEEP(cs_n),
    .X(_01_[6])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _13_ (
    .A(data_out[6]),
    .SLEEP(cs_n),
    .X(_01_[7])
  );
  sky130_fd_sc_hd__and2_0 _14_ (
    .A(cs_n),
    .B(data_in[0]),
    .X(_02_[0])
  );
  sky130_fd_sc_hd__mux2_1 _15_ (
    .A0(tx_shift[0]),
    .A1(data_in[1]),
    .S(cs_n),
    .X(_02_[1])
  );
  sky130_fd_sc_hd__mux2_1 _16_ (
    .A0(tx_shift[1]),
    .A1(data_in[2]),
    .S(cs_n),
    .X(_02_[2])
  );
  sky130_fd_sc_hd__mux2_1 _17_ (
    .A0(tx_shift[2]),
    .A1(data_in[3]),
    .S(cs_n),
    .X(_02_[3])
  );
  sky130_fd_sc_hd__mux2_1 _18_ (
    .A0(tx_shift[3]),
    .A1(data_in[4]),
    .S(cs_n),
    .X(_02_[4])
  );
  sky130_fd_sc_hd__mux2_1 _19_ (
    .A0(tx_shift[4]),
    .A1(data_in[5]),
    .S(cs_n),
    .X(_02_[5])
  );
  sky130_fd_sc_hd__mux2_1 _20_ (
    .A0(tx_shift[5]),
    .A1(data_in[6]),
    .S(cs_n),
    .X(_02_[6])
  );
  sky130_fd_sc_hd__mux2_1 _21_ (
    .A0(tx_shift[6]),
    .A1(data_in[7]),
    .S(cs_n),
    .X(_02_[7])
  );
  sky130_fd_sc_hd__nor2_1 _22_ (
    .A(bit_count[0]),
    .B(cs_n),
    .Y(_00_[0])
  );
  sky130_fd_sc_hd__xnor2_1 _23_ (
    .A(bit_count[0]),
    .B(bit_count[1]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor2_1 _24_ (
    .A(cs_n),
    .B(_03_),
    .Y(_00_[1])
  );
  sky130_fd_sc_hd__a21oi_1 _25_ (
    .A1(bit_count[0]),
    .A2(bit_count[1]),
    .B1(bit_count[2]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nor3_1 _26_ (
    .A(cs_n),
    .B(rx_valid),
    .C(_04_),
    .Y(_00_[2])
  );
  sky130_fd_sc_hd__dfrtp_1 _27_ (
    .CLK(sclk),
    .D(_01_[0]),
    .Q(data_out[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _28_ (
    .CLK(sclk),
    .D(_01_[1]),
    .Q(data_out[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _29_ (
    .CLK(sclk),
    .D(_01_[2]),
    .Q(data_out[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _30_ (
    .CLK(sclk),
    .D(_01_[3]),
    .Q(data_out[3]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _31_ (
    .CLK(sclk),
    .D(_01_[4]),
    .Q(data_out[4]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _32_ (
    .CLK(sclk),
    .D(_01_[5]),
    .Q(data_out[5]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _33_ (
    .CLK(sclk),
    .D(_01_[6]),
    .Q(data_out[6]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _34_ (
    .CLK(sclk),
    .D(_01_[7]),
    .Q(data_out[7]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _35_ (
    .CLK(sclk),
    .D(_02_[0]),
    .Q(tx_shift[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _36_ (
    .CLK(sclk),
    .D(_02_[1]),
    .Q(tx_shift[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _37_ (
    .CLK(sclk),
    .D(_02_[2]),
    .Q(tx_shift[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _38_ (
    .CLK(sclk),
    .D(_02_[3]),
    .Q(tx_shift[3]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _39_ (
    .CLK(sclk),
    .D(_02_[4]),
    .Q(tx_shift[4]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _40_ (
    .CLK(sclk),
    .D(_02_[5]),
    .Q(tx_shift[5]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _41_ (
    .CLK(sclk),
    .D(_02_[6]),
    .Q(tx_shift[6]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _42_ (
    .CLK(sclk),
    .D(_02_[7]),
    .Q(miso),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _43_ (
    .CLK(sclk),
    .D(_00_[0]),
    .Q(bit_count[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _44_ (
    .CLK(sclk),
    .D(_00_[1]),
    .Q(bit_count[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _45_ (
    .CLK(sclk),
    .D(_00_[2]),
    .Q(bit_count[2]),
    .RESET_B(reset_n)
  );
  assign tx_shift[7] = miso;
endmodule
